import {describe,it,expect,vi,afterEach} from 'vitest';
import {act,newGame,normalizeGame,type Game} from '../src/game';
import {contacts,generateNpc,beginEncounter,encounterActions,resolveEncounter,concealment} from '../src/battle/encounter';
import {createBattle,schedule,preload,stepNaval,arc,mergeCompletions,replaceOrder} from '../src/battle/naval';
import {enterBoarding,resolveDeck,resolveDuel,legalBoarding} from '../src/battle/boarding';
import {plannerPayload,validateDecision,requestBattleDecision} from '../src/battle/planner';
import {rng,roll,crew,type Battle,type Decision} from '../src/battle/types';
import {createShip} from '../src/ships';
const decision=(...ids:string[]):Decision=>({assessment:['Visible tactical conditions.'],objective:'survive',risk:'moderate',intent:'Preserve the crew.',action_ids:ids});
function fixture(){const g=newGame('Anne',42);g.ship!.id='player';g.cargo={'round-shot':100,'chain-shot':20,grapeshot:20,bombs:20,gunpowder:150,planks:20,tools:2,rope:20,sailcloth:20,medicine:10};const npc=generateNpc(g);npc.ship=createShip('sloop-universal','Enemy','npc');npc.crew=crew(10);npc.level=4;npc.temperament='Bold';npc.role='Pirate';g.battle=createBattle(g,npc);g.voyage={to:'saint-pierre',hours:49,remaining:25,weather:'Steady winds',dice:[3,4]};return g;}
function seedFor(natural:number){for(let seed=0;seed<100000;seed++){const r=roll({seed},'test',{});if(r.dice[0]+r.dice[1]===natural)return seed;}throw Error('Seed not found');}
function duel(g:Game,initiative='player'){const b=g.battle!;enterBoarding(b,b.playerId);b.phase='duel';b.status='planning';b.duel={initiative,exchange:0,control:0,firstRoll:true,demandedAt:[]};return b;}
afterEach(()=>vi.unstubAllGlobals());
describe('seeded encounters',()=>{
 it('preserves the two-day baseline and voyage contact cap',()=>{let seen=0;for(let i=0;i<5000;i++){const g=newGame('A',i);const c=contacts(g,48);seen+=c.length?1:0;expect(c.length).toBeLessThanOrEqual(1);}expect(seen/5000).toBeGreaterThan(.18);expect(seen/5000).toBeLessThan(.22);const g=newGame('A',25);g.pirateDanger=100;const c=contacts(g,240);expect(c.length).toBeLessThanOrEqual(4);expect(c.every((v,i)=>!i||v.at>c[i-1].at)).toBe(true);});
 it('replays contact timing, captain traits, ships, and openings exactly',()=>{const g=newGame('A',200);g.pirateDanger=10;expect(contacts(g,240)).toEqual(contacts({...newGame('A',200),pirateDanger:10},240));});
 it('makes new voyages independent of the obsolete two-ones trigger',()=>{const g=newGame('A',42);g.pirateDanger=0;const result=act(g,{type:'sail',to:'saint-pierre'},()=>0);expect(result.voyage).toBeNull();expect(result.port).toBe('saint-pierre');});
 it('exposes contextual responses and requires friendly attack confirmation',()=>{const g=fixture();delete g.battle;const n=generateNpc(g);n.faction='England';g.economy!.commerce!.attitude.England=80;beginEncounter(g,n);g.encounter!.stage='response';g.encounter!.posture='Pass';expect(encounterActions(g.encounter!)).toEqual(['ignore','attack']);expect(()=>resolveEncounter(g,{choice:'attack'})).toThrow('Confirm');});
 it('keeps peaceful market information as the dated departure snapshot',()=>{const g=fixture();delete g.battle;const n=generateNpc(g);beginEncounter(g,n);g.encounter!.stage='response';g.encounter!.posture='Hail';g.hours+=48;expect(resolveEncounter(g,{choice:'respond'})).toBe('continue');expect(g.economy!.memories[n.origin]).toEqual(n.market);expect(n.market.hour).toBe(n.departed);});
 it('bounds social responses and preserves concealment mastery curve',()=>{expect(concealment[10]).toBe(.95);const g=fixture();delete g.battle;beginEncounter(g,generateNpc(g));g.encounter!.stage='response';g.encounter!.posture='Demand';g.encounter!.responses=1;expect(encounterActions(g.encounter!)).not.toContain('negotiate');});
 it('protects material supplies from pirate trade-goods demands',()=>{const g=fixture();delete g.battle;g.cargo.sugar=10;beginEncounter(g,generateNpc(g));g.encounter!.stage='response';g.encounter!.posture='Demand';g.encounter!.demand={kind:'goods',value:100,fraction:1};resolveEncounter(g,{choice:'comply'});expect(g.cargo.sugar).toBe(0);expect(g.cargo.gunpowder).toBe(150);expect(g.cargo.planks).toBe(20);});
});
describe('naval schedules and simulation',()=>{
 it('reserves ammunition across schedules and disallows impossible reload sequences',()=>{const g=fixture(),b=g.battle!;b.ships.player.cargo.gunpowder=2;expect(()=>schedule(b,'player',['reload_port_round-shot','reload_starboard_round-shot'])).toThrow('gunpowder');expect(()=>schedule(b,'player',['reload_port_round-shot','reload_port_round-shot'])).toThrow('Unload');expect(()=>schedule(b,'player',Array(12).fill('turn_45'))).toThrow('1,000');});
 it('consumes preloads only once and preserves loaded rounds on a failed bearing',()=>{const g=fixture(),b=g.battle!;preload(b,'player','port','round-shot');expect(b.ships.player.cargo.gunpowder).toBe(148);expect(()=>preload(b,'player','port','round-shot')).toThrow('once');b.plans.player=schedule(b,'player',['fire_port']);b.plans.player[0].begun=true;/* Target left the arc after this action began. */b.plans.npc=[];b.status='playback';stepNaval(g,b);expect(b.ships.player.batteries.port.loaded).toBe(2);});
 it('uses half-open arcs with exactly one battery at each boundary',()=>{const b=fixture().battle!,s=b.ships.player;s.x=0;s.y=0;s.heading=0;const target=(deg:number)=>({x:100*Math.cos(deg*Math.PI/180),y:100*Math.sin(deg*Math.PI/180)});expect(arc(s,target(45))).toBe('starboard');expect(arc(s,target(135))).toBe('stern');expect(arc(s,target(225))).toBe('port');expect(arc(s,target(315))).toBe('bow');});
 it('resolves completion events from the same snapshot and supports mutual destruction',()=>{const g=fixture(),b=g.battle!,pre=structuredClone(b),one=structuredClone(b),two=structuredClone(b);pre.ships.player.ship.hullPoints=10;b.ships.player.ship.hullPoints=10;one.ships.player.ship.hullPoints=0;two.ships.player.ship.hullPoints=14;mergeCompletions(b,pre,[one,two]);expect(b.ships.player.ship.hullPoints).toBe(4);const reverse=structuredClone(pre);mergeCompletions(reverse,pre,[two,one]);expect(reverse.ships.player.ship.hullPoints).toBe(4);});
 it('retains unused resources when grappling cancels later actions',()=>{const g=fixture(),b=g.battle!;b.ships.npc.x=10;b.ships.npc.heading=0;b.ships.player.sails=0;b.ships.npc.sails=0;g.seed=seedFor(12);b.plans.player=schedule(b,'player',['grapple','reload_port_round-shot']);b.plans.npc=[];b.status='playback';stepNaval(g,b);expect(b.phase).toBe('deck');expect(b.plans).toEqual({});expect(b.ships.player.cargo.gunpowder).toBe(150);});
 it('suspends invalid starts and shifts later orders for a single replacement',()=>{const g=fixture(),b=g.battle!;b.plans.player=schedule(b,'player',['turn_45','rally']);b.plans.npc=[];b.ships.player.sails=0;b.status='playback';stepNaval(g,b);expect(b.status).toBe('replacement');replaceOrder(b,'player','sails_1');expect(b.plans.player[0].id).toBe('sails_1');expect(b.plans.player[1].id).toBe('rally');expect(b.plans.player[1].start).toBe(b.plans.player[0].end);});
 it('serializes unresolved RNG and accepted decisions without regeneration',()=>{let g=fixture();g=act(g,{type:'battle-commit',ids:['turn_45']});g=act(g,{type:'battle-accept',decision:decision('turn_-45'),key:g.battle!.decisionKey});expect(()=>act(g,{type:'battle-accept',decision:decision(),key:g.battle!.decisionKey})).toThrow();const restored=normalizeGame(JSON.parse(JSON.stringify(g)));expect(restored.battle!.accepted).toEqual(g.battle!.accepted);const play=act(g,{type:'battle-reveal'}),copy=act(restored,{type:'battle-reveal'});expect(act(play,{type:'battle-instant'})).toEqual(act(copy,{type:'battle-instant'}));});
});
describe('boarding and captain duels',()=>{
 it('uses tier rounds, Guard casualty reduction, and natural decisive shifts',()=>{const g=fixture(),b=g.battle!;enterBoarding(b,b.playerId);expect(b.rounds).toBe(2);b.committed=['guard'];b.accepted=decision('assault');g.seed=seedFor(12);resolveDeck(g,b);expect(b.control).toBe(0);expect(b.ships.npc.crew.fit).toBe(9);});
 it('counts injured as living crew and dead separately',()=>{const g=fixture(),b=g.battle!;enterBoarding(b,b.playerId);b.committed=['assault'];b.accepted=decision('assault');g.seed=seedFor(2);resolveDeck(g,b);const c=b.ships.player.crew;expect(c.fit+c.injured+c.dead).toBe(10);expect(c.fit).toBe(9);expect(b.control).toBe(-2);});
 it('moves to a duel with one-use control and attacker tie initiative',()=>{const g=fixture(),b=g.battle!;enterBoarding(b,b.npcId);b.round=b.rounds;b.control=5;b.committed=['guard'];b.accepted=decision('guard');g.seed=seedFor(8);resolveDeck(g,b);expect(b.phase).toBe('duel');expect(b.duel!.control).toBe(2);expect(b.duel!.initiative).toBe('player');});
 it('natural 2 pistol misfire consumes the shot without melee counterattack',()=>{const g=fixture(),b=duel(g);b.ships.player.captain.pistol=true;b.committed=['pistol'];b.accepted=decision('dodge');g.seed=seedFor(2);resolveDuel(g,b);expect(b.ships.player.captain.pistol).toBe(false);expect(b.ships.player.captain.injury).toBe(0);expect(b.duel!.initiative).toBe('npc');});
 it('critical two-step injury can pass through incapacitation to death',()=>{const g=fixture(),b=duel(g);b.ships.npc.captain.injury=4;b.committed=['heavy'];b.accepted=decision('block');g.seed=seedFor(12);resolveDuel(g,b);expect(b.phase).toBe('capture');expect(b.ships.npc.captain.injury).toBe(6);expect(b.result!.ships.npc.captain.injury).toBe(6);});
 it('defensive natural 12 takes initiative and counterattacks once',()=>{const g=fixture(),b=duel(g,'npc');b.duel!.npcAttack='heavy';b.committed=['parry'];b.accepted=decision('heavy');g.seed=seedFor(12);resolveDuel(g,b);expect(b.ships.player.captain.injury).toBe(0);expect(b.ships.npc.captain.injury).toBe(1);expect(b.duel!.initiative).toBe('player');expect(b.duel!.firstRoll).toBe(false);});
 it('allows only Dodge against a pistol and enforces fanatical surrender refusal',()=>{const g=fixture(),b=duel(g,'npc');b.duel!.npcAttack='pistol';expect(legalBoarding(b,'player')).toEqual(['dodge','surrender']);b.npc.temperament='Fanatical';expect(()=>validateDecision(b,decision('surrender'))).toThrow('Fanatical');});
 it('permits a demand only once per injury condition',()=>{const g=fixture(),b=duel(g);b.committed=['demand-surrender'];b.accepted=decision('block');g.seed=seedFor(2);resolveDuel(g,b);b.duel!.initiative='player';expect(legalBoarding(b,'player')).not.toContain('demand-surrender');b.ships.npc.captain.injury++;expect(legalBoarding(b,'player')).toContain('demand-surrender');});
 it('resolves simultaneous fatigue collapse using home deck when control ties',()=>{const g=fixture(),b=duel(g);b.attacker='player';b.duel!.exchange=4;b.ships.player.captain.fatigue=3;b.ships.npc.captain.fatigue=3;b.committed=['quick'];b.accepted=decision('dodge');g.seed=seedFor(8);resolveDuel(g,b);expect(b.phase).toBe('capture');expect(b.winner).toBe('npc');});
});
describe('mandatory NPC model boundary',()=>{
 it('does not expose secret schedules, player inventory, or exact mastery',()=>{const g=fixture(),b=g.battle!;b.committed=['turn_45'];b.ships.player.cargo.jewelry=123456;const payload=plannerPayload(b),json=JSON.stringify(payload);expect(json).not.toContain('123456');expect(payload.enemy).not.toHaveProperty('skills');expect(payload).not.toHaveProperty('committed');expect(payload.declaredAttack).toBeUndefined();});
 it('pauses without a Battle model instead of using a fallback',async()=>{await expect(requestBattleDecision(fixture().battle!,'','',new AbortController().signal,()=>{})).rejects.toThrow('Battle model');});
 it('returns exact validation errors for correction and accepts a legal plan',async()=>{const mock=vi.fn().mockResolvedValueOnce({ok:true,json:async()=>({choices:[{message:{content:JSON.stringify(decision('invented'))}}]})}).mockResolvedValueOnce({ok:true,json:async()=>({choices:[{message:{content:JSON.stringify(decision('turn_45'))}}]})});vi.stubGlobal('fetch',mock);const result=await requestBattleDecision(fixture().battle!,'key','model',new AbortController().signal,()=>{});expect(result.action_ids).toEqual(['turn_45']);expect(mock).toHaveBeenCalledTimes(2);expect(mock.mock.calls[1][1].body).toContain('Unknown action');});
 it('suspends after ten invalid responses without changing state',async()=>{const g=fixture(),before=structuredClone(g);const mock=vi.fn().mockResolvedValue({ok:true,json:async()=>({choices:[{message:{content:'not json'}}]})});vi.stubGlobal('fetch',mock);await expect(requestBattleDecision(g.battle!,'key','model',new AbortController().signal,()=>{})).rejects.toThrow('Ten invalid');expect(mock).toHaveBeenCalledTimes(10);expect(g).toEqual(before);});
});
it('plays the persisted encounter → naval → deck → duel → resolution flow through the public reducer',()=>{
 let g=fixture();delete g.battle;const npc=generateNpc(g);npc.ship=createShip('sloop-universal','Enemy','npc');npc.crew=crew(10);npc.temperament='Fanatical';beginEncounter(g,npc);g.encounter!.stage='response';g.encounter!.posture='Attack';g=act(g,{type:'contact',response:{choice:'fight'}});let b=g.battle!;b.ships.player.sails=0;b.ships.npc.sails=0;b.ships.npc.x=10;g.seed=seedFor(12);
 const exchange=(ids:string[],npcIds:string[])=>{g=act(g,{type:'battle-commit',ids});g=act(g,{type:'battle-accept',decision:decision(...npcIds),key:g.battle!.decisionKey});g=act(g,{type:'battle-reveal'});};
 exchange(['grapple'],[]);g=act(g,{type:'battle-instant'});expect(g.battle!.phase).toBe('deck');g=act(g,{type:'battle-transition'});
 while(g.battle!.phase==='deck'){g.seed=seedFor(8);exchange(['guard'],['guard']);}expect(g.battle!.phase).toBe('duel');g=act(g,{type:'battle-transition'});
 for(let i=0;i<3;i++){g.seed=seedFor(12);exchange(['heavy'],['dodge']);}
 expect(g.battle!.phase).toBe('capture');expect(g.battle!.winner).toBe('player');expect(g.battle!.result!.ships.npc.captain.injury).toBe(6);expect(g.crewState!.fit+g.crewState!.injured).toBe(g.crew);expect(()=>act(g,{type:'battle-resume'})).toThrow('Capture Resolution');
});
it('accepts one free NPC preload per battery before timed orders and spends its supplies exactly once',()=>{
 let g=fixture();const before=g.battle!.ships.npc.cargo.gunpowder;g=act(g,{type:'battle-commit',ids:[]});g=act(g,{type:'battle-accept',key:g.battle!.decisionKey,decision:decision('preload_port_round-shot','turn_45')});g=act(g,{type:'battle-reveal'});expect(g.battle!.ships.npc.cargo.gunpowder).toBe(before-2);expect(g.battle!.ships.npc.batteries.port.loaded).toBe(2);expect(g.battle!.plans.npc[0].start).toBe(0);expect(g.battle!.plans.npc[0].id).toBe('turn_45');
});
