import {CapturePanel} from './CapturePanel';
import {returnFee} from './battle/capture';
import {sailingProblems} from './performance';
import {useEffect,useRef,useState} from 'react';
import type {Action,Game} from './game';
import {shipDefinition,BATTERIES} from './ships';
import {encounterActions,standing,standingRank,goodsValue} from './battle/encounter';
import {rank,injuryNames,fatigueNames,type Battle,type Ammo} from './battle/types';
import {AMMO,orderCatalogue,schedule,range,distance,bearing,coursePreview} from './battle/naval';
import {legalBoarding} from './battle/boarding';
import {requestBattleDecision} from './battle/planner';
const label=(id:string)=>id.replaceAll('_',' ').replaceAll('-',' ');
type Props={game:Game;busy:boolean;apiKey:string;model:string;onAction:(action:Action)=>Promise<void>;onSettings:()=>void};
export function BattlePanel({game:g,busy,apiKey,model,onAction,onSettings}:Props){
 const b=g.battle,e=g.encounter;
 const [ids,setIds]=useState<string[]>([]),[error,setError]=useState(''),[planning,setPlanning]=useState(false),[attempt,setAttempt]=useState(0),[errors,setErrors]=useState<string[]>([]),[seconds,setSeconds]=useState(0),[confirm,setConfirm]=useState(false),[dump,setDump]=useState<''|'goods'|'gunpowder'>(''),[play,setPlay]=useState<0|1|2>(0),[ammo,setAmmo]=useState<Ammo>('round-shot');
 const abort=useRef<AbortController|null>(null),requestLock=useRef(false);
 useEffect(()=>()=>{abort.current?.abort();},[]);
 useEffect(()=>{setIds([]);setError('');setPlay(0);},[b?.decisionKey,b?.phase]);
 useEffect(()=>{if(!planning)return;const start=Date.now();const timer=setInterval(()=>setSeconds((Date.now()-start)/1000),100);return()=>clearInterval(timer);},[planning]);
 async function act(a:Action){setError('');try{await onAction(a);}catch(err){setError(err instanceof Error?err.message:'Action failed.');setPlay(0);}}
 useEffect(()=>{if(!play||!b||b.status!=='playback'||busy)return;const timer=setTimeout(()=>{void act({type:'battle-step'});},play===2?20:900);return()=>clearTimeout(timer);},[play,b,busy]);
 async function request(){if(!b||requestLock.current)return;requestLock.current=true;setPlanning(true);setSeconds(0);setError('');const controller=new AbortController();abort.current=controller;const timeout=setTimeout(()=>controller.abort(),120000);
  try{const decision=await requestBattleDecision(b,apiKey,model,controller.signal,(n,errors)=>{setAttempt(n);setErrors(errors);});if(!controller.signal.aborted)await onAction({type:'battle-accept',decision,key:b.decisionKey});}
  catch(err){setError(err instanceof Error?err.message:'Battle model request failed.');}
  finally{clearTimeout(timeout);requestLock.current=false;setPlanning(false);}
 }
 const disabled=busy||planning;
 if(!b&&e){const choices=encounterActions(e),attitude=standing(g,e.npc.faction);return <section className="panel battle-panel"><p className="eyebrow">{e.stage==='sighting'?'EARLY SIGHTING':'SHIP ENCOUNTER'}</p><h1>{shipDefinition(e.npc.ship.configurationId).label}</h1><p>{e.npc.faction} flag · {attitude} ({standingRank(attitude)})</p><p>{e.message}</p>{(g.skills?.lookout?.tier??0)>=3&&<p>Captain rank: {rank(e.npc.level)}. Hull appears {e.npc.ship.hullPoints/shipDefinition(e.npc.ship.configurationId).maxHull>.85?'healthy':'damaged'}.</p>}
 {e.demand&&<p className="warning">Demand: {e.demand.kind} · pirate value {Math.ceil(e.demand.value*e.demand.fraction)} silver{e.demand.fraction<1?` (${Math.round(e.demand.fraction*100)}% of original)`:''}.</p>}
 {e.stage==='counteroffer'&&<p>Counteroffer must be worth at least {Math.ceil((e.demand?.value??0)*.5)} silver. Goods aboard: {Math.floor(goodsValue(g))} silver reference value.</p>}
 {choices.includes('flee')&&<label>Voluntary escape distraction (lost even on failure)<select value={dump} onChange={event=>setDump(event.target.value as typeof dump)}><option value="">None</option><option value="goods">Dump all trade goods</option><option value="gunpowder">One gunpowder charge</option></select></label>}
 <div className="button-row">{choices.map(choice=><button key={choice} disabled={disabled} onClick={()=>{if(choice==='attack'&&attitude>40&&!confirm){setConfirm(true);return;}void act({type:'contact',response:{choice,confirmed:confirm,dump:choice==='flee'&&dump?dump:undefined}});}}>{label(choice)}</button>)}</div>
 {confirm&&<p role="alert">Attack this friendly ship? If identified, you risk −20 faction attitude and −5 reputation. Select Attack again to confirm, or <button onClick={()=>setConfirm(false)}>Cancel</button>.</p>}
 {g.encounterRoll&&<RollDetails roll={g.encounterRoll}/>} {g.inspectionRolls?.map((r,i)=><RollDetails key={i} roll={r}/>)} {error&&<p role="alert">{error}</p>}</section>;}
 if(!b)return <section className="panel"><h1>At sea</h1><button disabled={busy} onClick={()=>act({type:'continue-voyage'})}>Continue voyage</button></section>;
 const p=b.ships[b.playerId],n=b.ships[b.npcId];let planned:ReturnType<typeof schedule>=[],validation='';if(b.phase==='naval'&&ids.length&&!b.replacement)try{planned=schedule(b,b.playerId,ids);}catch(err){validation=(err as Error).message;}
 const options=b.phase==='naval'?orderCatalogue(b,b.playerId):[];
 const title={naval:'Naval Engagement',deck:'Deck Battle',duel:'Captain Duel',capture:'Battle resolution',ended:'Encounter ended'}[b.phase];
 return <section className="panel battle-panel"><p className="eyebrow">{b.phase==='naval'?`WINDOW ${b.window} · ${b.unit} / 1,000`:b.phase==='deck'?`ROUND ${b.round} / ${b.rounds}`:b.phase==='duel'?`EXCHANGE ${b.duel!.exchange} · FATIGUE IN ${5-b.duel!.exchange%5}`:'OUTCOME'}</p><h1>{title}</h1>
 <div className="battle-status"><article><h2>{p.ship.name}</h2><p>Hull {p.ship.hullPoints.toFixed(0)} / {shipDefinition(p.ship.configurationId).maxHull} · Sails {p.ship.sailCondition}%</p><p>{p.crew.fit} fit · {p.crew.injured} injured · {p.crew.dead} dead</p><p>{injuryNames[p.captain.injury]} · {fatigueNames[p.captain.fatigue]}</p>{b.phase==='duel'&&<p>{label(p.captain.weapon)} · quality {p.captain.quality} · pistol {p.captain.pistol?'loaded':'unavailable'}</p>}</article><article><h2>{n.ship.name}</h2><p>{b.npc.faction} · {rank(b.npc.level)} captain</p><p>Hull {n.ship.hullPoints/n.startHull>.7?'largely intact':n.ship.hullPoints/n.startHull>.3?'damaged':'critical'} · crew {n.crew.fit/n.startFit>.7?'strong':n.crew.fit?'depleted':'defeated'}</p><p>{injuryNames[n.captain.injury]} · {fatigueNames[n.captain.fatigue]}</p>{b.phase==='duel'&&<p>{label(n.captain.weapon)} · quality {n.captain.quality} · pistol {n.captain.pistol?'loaded':'unavailable'}</p>}</article></div>
 {b.phase==='naval'&&<><p>{range(distance(p,n))} range · distance {distance(p,n).toFixed(0)} · bearing {bearing(p,n).toFixed(0)}° · wind {b.wind}° ({['Calm','Light','Moderate','Strong'][b.windStrength]})</p><BattleMap battle={b} ids={b.status==='planning'?ids:[]}/><p>Sails: {['Furled','Battle','Full'][p.sails]}. {Object.entries(p.states).filter(([,v])=>v).map(([k,v])=>`${k}: ${v}`).join(' · ')||'No critical conditions.'}</p></>}
 {b.phase==='deck'&&<p>Boarding Control: {b.control}. Both orders remain secret until committed.</p>}
 {b.phase==='duel'&&<p>Initiative: {b.duel!.initiative===b.playerId?'You':'Opponent'}. {b.duel!.npcAttack&&`Opponent declares ${label(b.duel!.npcAttack)}.`} {b.duel!.firstRoll&&`First-roll Boarding Control: ${b.duel!.control}.`}</p>}
 {b.status==='transition'&&<><p>{b.log[0]}</p><button disabled={disabled} onClick={()=>act({type:'battle-transition'})}>Continue to {title}</button></>}
 {(b.status==='planning'||b.status==='replacement')&&<>
 {b.phase==='naval'&&<>{b.window===1&&b.unit===0&&!b.replacement&&<details><summary>Free battery preloads (consume ammunition and powder)</summary><select aria-label="Preload ammunition" value={ammo} onChange={event=>setAmmo(event.target.value as Ammo)}>{AMMO.map(a=><option key={a} value={a}>{label(a)}</option>)}</select>{BATTERIES.filter(k=>p.ship.cannons[k]>0).map(k=><p key={k}>{k}: {p.ship.cannons[k]} guns · {p.batteries[k].loaded} loaded <button disabled={disabled||b.preloaded.includes(`${b.playerId}:${k}`)} onClick={()=>act({type:'battle-preload',battery:k,ammo})}>Preload {k}</button></p>)}</details>}
 {b.status==='replacement'&&<p role="alert">An order is no longer valid. Choose exactly one replacement; later orders shift and any that exceed 1,000 units are removed.</p>}
 {(!b.replacement||b.replacement.includes(b.playerId))&&<><label>Orders<select value="" onChange={event=>{if(event.target.value)setIds(b.replacement?[event.target.value]:[...ids,event.target.value]);}}><option value="">Add an order…</option>{options.map(o=><option key={o.id} value={o.id}>{label(o.id)} · {o.cost} units</option>)}</select></label>
 <ol>{ids.map((id,i)=><li key={`${id}-${i}`}>{label(id)} {planned[i]&&`${planned[i].start}–${planned[i].end}`} <button aria-label={`Remove order ${i+1}`} onClick={()=>setIds(ids.filter((_,j)=>i!==j))}>Remove</button>{planned[i]&&<small>{Object.entries(planned[i].parts).map(([k,v])=>`${k} ${Math.round(v*100)}%`).join(' · ')}{Object.keys(planned[i].resources).length>0&&` · Reserved: ${Object.entries(planned[i].resources).map(([k,v])=>`${v} ${k}`).join(', ')}`}</small>}</li>)}</ol>{validation&&<p role="alert">{validation}</p>}<p>Unused units are idle; the ship continues moving.</p><button className="primary" disabled={disabled||!!validation||!!b.replacement&&!ids.length} onClick={()=>act({type:'battle-commit',ids})}>Commit secret {b.replacement?'replacement':'schedule'}</button></>}
 {b.replacement&&!b.replacement.includes(b.playerId)&&<button disabled={disabled} onClick={()=>act({type:'battle-request'})}>Request NPC replacement</button>}
 </>}
 {(b.phase==='deck'||b.phase==='duel')&&(b.phase!=='duel'||b.duel!.initiative===b.playerId||b.duel!.npcAttack)?<div className="button-row">{legalBoarding(b,b.playerId).filter(a=>a!=='surrender').map(id=><button key={id} disabled={disabled} onClick={()=>act({type:'battle-commit',ids:[id]})}>{label(id)}</button>)}</div>:b.phase==='duel'&&<button disabled={disabled} onClick={()=>act({type:'battle-request'})}>Await opponent’s attack</button>}
 {!b.replacement&&<button disabled={disabled} onClick={()=>act({type:'battle-surrender'})}>Surrender</button>}
 </>}
 {b.status==='waiting'&&<div className="battle-model"><h2>NPC decision</h2><p>{planning?`Thinking · ${seconds.toFixed(1)} seconds · attempt ${attempt} / 10`:'Your orders are saved. Request the opponent’s decision to continue.'}</p>{(!apiKey||!model)&&<p>Combat is suspended until a Battle model is selected.</p>}<button disabled={planning||busy||!apiKey||!model} onClick={()=>void request()}>{error?'Retry':'Request Battle model decision'}</button><button disabled={planning} onClick={onSettings}>Change Model</button>{planning&&<button onClick={()=>abort.current?.abort()}>Suspend request</button>}{errors.length>0&&<details><summary>Validation corrections</summary><ul>{errors.map((e,i)=><li key={i}>{e}</li>)}</ul></details>}</div>}
 {b.accepted&&b.status!=='waiting'&&<details open><summary>NPC tactical intent</summary><p>{b.accepted.intent} · Risk: {b.accepted.risk}</p><ul>{b.accepted.assessment.map((a,i)=><li key={i}>{a}</li>)}</ul></details>}
 {b.status==='reveal'&&<><h2>Orders revealed</h2><p>You: {b.committed?.map(label).join(' → ')||'Idle'}</p><p>Opponent: {b.accepted?.action_ids.map(label).join(' → ')||'Existing orders retained'}</p><button className="primary" disabled={disabled} onClick={()=>act({type:'battle-reveal'})}>Resolve {b.phase==='naval'?'timeline':'exchange'}</button></>}
 {b.status==='playback'&&<><div className="button-row"><button onClick={()=>setPlay(0)}>Pause</button><button onClick={()=>setPlay(1)}>Normal</button><button onClick={()=>setPlay(2)}>Fast</button><button disabled={busy} onClick={()=>act({type:'battle-step'})}>Next event</button><button disabled={busy} onClick={()=>act({type:'battle-instant'})}>Resolve instantly</button></div><table><thead><tr><th>Ship</th><th>Action</th><th>Start</th><th>Complete</th></tr></thead><tbody>{Object.entries(b.plans).flatMap(([id,plan])=>plan.map((o,i)=><tr key={`${id}-${i}`}><td>{id===b.playerId?'You':'Opponent'}</td><td>{label(o.id)}</td><td>{o.start}</td><td>{o.end}</td></tr>))}</tbody></table></>}
 {b.phase==='capture'&&<CapturePanel key={b.id} game={g} busy={disabled} onAction={onAction}/>}
 {b.phase==='ended'&&<><p>{b.reason}</p><p>Commanding: {g.ship?.name}.</p>{b.settlement?.route!=='return'&&<button disabled={busy||!!sailingProblems(g).length} onClick={()=>act({type:'battle-resume'})}>Continue voyage</button>}{sailingProblems(g).length>0&&<p role="status">{sailingProblems(g).join(' ')}</p>}<button disabled={busy} onClick={()=>act({type:'battle-return'})}>Return to departure port — {returnFee(g)} silver + wages, 12 hours</button></>}
 {error&&<p role="alert">{error}</p>}
 {b.rolls[0]&&<RollDetails roll={b.rolls[0]}/>}<details><summary>Battle log ({b.log.length})</summary><ol>{b.log.map((l,i)=><li key={i}>{l}</li>)}</ol></details>
 </section>;
}
function RollDetails({roll:r}:{roll:import('./battle/types').Roll}){return <details open className="battle-roll"><summary>{r.label}: {r.dice.join(' + ')} {r.modifier>=0?'+':''}{r.modifier} = {r.total}</summary><ul>{Object.entries(r.parts).map(([name,value])=><li key={name}>{name}: {value>=0?'+':''}{value}</li>)}</ul><small>Net modifier capped at −4…+4. Natural 2 and 12 override totals.</small></details>;}
function BattleMap({battle:b,ids}:{battle:Battle;ids:string[]}){let preview:ReturnType<typeof coursePreview>|undefined;try{preview=coursePreview(b,b.playerId,ids);}catch{}const ships=Object.values(b.ships),xs=[...ships.map(s=>s.x),...(preview?.path.map(p=>p[0])??[])],ys=[...ships.map(s=>s.y),...(preview?.path.map(p=>p[1])??[])],x=Math.min(...xs)-100,y=Math.min(...ys)-100,w=Math.max(300,Math.max(...xs)-x+100),h=Math.max(250,Math.max(...ys)-y+100);return <><svg className="battle-map" viewBox={`${x} ${y} ${w} ${h}`} role="img" aria-label="Ship positions and headings">{preview&&<polyline points={preview.path.map(p=>p.join(',')).join(' ')} fill="none" stroke="#2c838b" strokeDasharray="6 5" strokeWidth="2"/>}{ships.map(s=><g key={s.ship.id}><path d="M 20 0 L -12 -10 L -8 0 L -12 10 Z" transform={`translate(${s.x} ${s.y}) rotate(${s.heading})`} fill={s.ship.id===b.playerId?'#2c838b':'#bd663b'}/><text x={s.x} y={s.y+30} textAnchor="middle">{s.ship.id===b.playerId?'You':'Opponent'}</text></g>)}{b.hazards.map(h=><circle key={h.id} cx={h.x} cy={h.y} r={20} fill="#bf543b" opacity=".5"/>)}</svg>{preview&&<small>Projected course (dashed): {preview.range}, distance {preview.distance.toFixed(0)}, bearing {preview.bearing.toFixed(0)}° if the opponent holds course. Enemy orders may change this.</small>}</>;}
