import {StatusMeter} from './GameDetails';
import type {Game,Action} from './game';
import {crew,crewExperience} from './battle/types';
import {CREW_DOMAINS,crewServiceQuote,type CrewAction} from './crew';
export function CrewSummary({game:g}:{game:Game}){
 const c=g.crewState??crew(g.crew);
 return <><h2>Crew development</h2><div className="meter-grid crew-meters">{CREW_DOMAINS.map(domain=><StatusMeter key={domain} label={`${domain[0].toUpperCase()+domain.slice(1)} experience`} value={crewExperience(c,domain)} detail={`${crewExperience(c,domain).toFixed(2)} / 100`} progress/>)}{(['morale','discipline'] as const).map(key=>{const value=c[key],state=value<20?'Critical':value<40?'Low':value<70?'Steady':'High';return <StatusMeter key={key} label={key==='morale'?'Morale':'Discipline'} value={value} detail={`${value.toFixed(1)} / 100 · ${state}`} tone={value<20?'danger':value<40?'warning':'normal'}/>;})}</div><dl className="full-stats"><div><dt>Unpaid wage exposure</dt><dd>{(c.unpaidWageHours??0).toFixed(1)} equivalent hours</dd></div><div><dt>Current treasury debt</dt><dd>{Math.max(0,-g.silver).toFixed(2)} silver</dd></div></dl><p>Sailing experience improves speed and maneuverability; gunnery improves accuracy and reload time; fighting improves boarding strength. New recruits join at 50 experience and dilute veteran averages.</p><p>Each full day of unpaid wages lowers morale by 4 and discipline by 2, proportional to the unpaid share. Treasury debt is settled automatically by incoming silver. Paying debt stops further wage penalties but does not restore morale already lost.</p></>;
}
export function CrewServices({game:g,busy,perform}:{game:Game;busy:boolean;perform:(a:Action)=>void}){
 const services:{name:string;action:CrewAction}[]=[...CREW_DOMAINS.map(domain=>({name:`Train ${domain}`,action:{type:'train-crew' as const,domain}})),{name:'Medical care',action:{type:'medical-care'}},{name:'Shore leave',action:{type:'shore-leave'}}];
 return <section aria-label="Crew training and medical care"><CrewSummary game={g}/><div className="two-columns">{services.map(({name,action})=>{const q=crewServiceQuote(g,action);return <article className="service" key={name}><h3>{name}</h3><p>{q.hours} hours · {q.fee} silver fee + {q.wages.toFixed(2)} wages · {q.food.toFixed(2)} provisions.</p><p>{action.type==='train-crew'?`+${q.gain.toFixed(2)} ${action.domain} experience, +1 discipline and +0.5 captain Training practice. Port training stops at 75; service experience can reach 100.`:action.type==='shore-leave'?`Restore ${q.gain.toFixed(1)} morale, up to 80. Fees include shore recreation; wages and provisions are charged separately.`:`Recover ${q.healed} injured crew and heal ${q.captainHealed} captain Injury step. Injured crew still consume provisions and wages. Dead sailors cannot be healed.`}</p>{q.errors.length>0&&<ul className="warning">{q.errors.map(error=><li key={error}>{error}</li>)}</ul>}<button disabled={busy||q.errors.length>0} onClick={()=>perform(action)}>{name}</button></article>;})}</div></section>;
}
