import {useState} from 'react';
import {ALL_GOODS,CATALOGUE} from './goods';
import {aboard,cargoCost,consumeLots,rememberedSale} from './trade';
import {spoilCargo,fruitAfter} from './operations';
import {hoursTo,foodFor,wageFor,date,duration,type Game,type PortId} from './game';
export function departureEstimate(original:Game,to:PortId,factor=1,delay=0){
 const hours=Math.ceil(hoursTo(original.port,to,original)*factor)+delay;
 if(!Number.isFinite(hours))return null;
 const g=structuredClone(original),food=foodFor(g,hours),wages=wageFor(g,hours),foodCost=cargoCost(g,'provisions',Math.min(food,g.provisions)),lostFruit=aboard(g,'fruit')-fruitAfter(aboard(g,'fruit'),hours),spoilCost=cargoCost(g,'fruit',lostFruit);
 consumeLots(g,'provisions',Math.min(g.provisions,food));g.provisions=Math.max(0,g.provisions-food);spoilCargo(g,hours);
 const rows=ALL_GOODS.filter(id=>id!=='provisions'&&aboard(original,id)>0).map(id=>{const quantity=Math.floor(aboard(g,id)+1e-8);return {id,quantity,remaining:aboard(g,id),quote:quantity>0?rememberedSale(g,id,to,quantity):null};});
 const sales=rows.reduce((n,r)=>n+(r.quote?.revenue??0),0),margin=rows.reduce((n,r)=>n+(r.quote?.profit??0),0),missing=rows.some(r=>r.quantity>0&&!r.quote),unknown=rows.some(r=>r.quote?.profit===null)||foodCost.unknown>1e-8||spoilCost.unknown>1e-8;
 const rewards=g.contracts.filter(c=>c.to===to).reduce((n,c)=>n+c.reward,0),canFeed=original.provisions+1e-8>=food;
 return {hours,food,wages,foodCost,lostFruit,spoilCost,rows,sales,rewards,missing,unknown,canFeed,cashAfterTravel:original.silver-wages,cashAfterQuotedBusiness:original.silver-wages+sales+rewards,estimatedResult:missing||unknown||!canFeed?null:margin+rewards-wages-foodCost.total-spoilCost.total};
}
export function DepartureFinance({game,to}:{game:Game;to:PortId}){
 const [scenario,setScenario]=useState('normal');const q=departureEstimate(game,to,scenario==='normal'?1:1.25,scenario==='reserve'?24:0);
 if(!q)return <p>Restore the ship's sailing ability to estimate voyage finances.</p>;
 return <details className="supply-service"><summary>Voyage finances · estimates</summary><label>Travel scenario<select value={scenario} onChange={e=>setScenario(e.target.value)}><option value="normal">Normal winds</option><option value="headwinds">Headwinds</option><option value="reserve">Headwinds + one day delay</option></select></label><dl className="full-stats"><div><dt>Travel time / wages</dt><dd>{duration(q.hours)} / {q.wages.toFixed(2)} silver</dd></div><div><dt>Food consumed / remaining</dt><dd>{q.food.toFixed(2)} / {(game.provisions-q.food).toFixed(2)}</dd></div><div><dt>Fruit lost</dt><dd>{q.lostFruit.toFixed(2)} units</dd></div><div><dt>Silver on arrival before business</dt><dd>{q.cashAfterTravel.toFixed(2)}</dd></div><div><dt>Remembered cargo sale subtotal</dt><dd>{q.sales} silver{q.missing?' · incomplete':''}</dd></div><div><dt>Contracts payable after delivery</dt><dd>{q.rewards} silver</dd></div><div><dt>Silver after quoted sales and delivery</dt><dd>{q.cashAfterQuotedBusiness.toFixed(2)}{q.missing?' · incomplete':''}</dd></div><div><dt>Estimated result after recorded cargo and voyage costs</dt><dd>{q.estimatedResult===null?'Unknown — missing prices, costs, or food':`${q.estimatedResult.toFixed(2)} silver`}</dd></div></dl>{!q.canFeed&&<p className="warning">Not enough provisions to complete this scenario.</p>}{q.cashAfterTravel<0&&<p className="warning">This voyage is projected to leave wage debt. Unpaid wages reduce crew morale and discipline.</p>}<div className="table-wrap"><table><thead><tr><th>Cargo</th><th>Whole units to sell</th><th>Remembered sale total</th><th>Recorded cargo margin</th><th>Price observation</th></tr></thead><tbody>{q.rows.map(r=><tr key={r.id}><th scope="row">{CATALOGUE[r.id].name}</th><td>{r.quantity}</td><td>{r.quote?.revenue??'Unknown'}</td><td>{r.quote?.profit?.toFixed(2)??'Unknown'}</td><td>{r.quote?date(r.quote.hour):'No usable record'}</td></tr>)}</tbody></table></div><p className="muted">Uses only remembered legal-market prices and their recorded stock limits. Fractional unsold cargo retains its value and is excluded from sale income. Provisions are reserved for use, not projected for sale. Prices may change. Estimates exclude arrival trading/delivery hours, future repairs, inspections and encounter losses. Quest payments require successful delivery.</p></details>;
}
