import {useState} from 'react';
import {financialSummary,ENTRY_NAMES,type EntryKind} from './finance';
import {CATALOGUE} from './goods';
import {date,port,type Game} from './game';
const money=(n:number)=>n.toLocaleString('en',{minimumFractionDigits:2,maximumFractionDigits:2});
export function FinanceJournal({game:g}:{game:Game}){
 const [scope,setScope]=useState('all'),[view,setView]=useState<'ledger'|'trades'>('ledger'),[page,setPage]=useState(0),f=g.finances;
 if(!f)return <><h2>Finance</h2><p>Financial recording begins with your next game action. Past transactions cannot be reconstructed.</p></>;
 const entries=f.entries.filter(e=>scope==='all'||(scope==='initial'?e.account===null:e.account===Number(scope))),summary=financialSummary(entries),account=f.voyages.find(v=>v.id===Number(scope));
 const history=[...entries.filter(e=>view==='ledger'||e.kind==='purchase'||e.kind==='sale')].reverse(),pages=Math.max(1,Math.ceil(history.length/30)),current=Math.min(page,pages-1);
 return <><h2>Voyage accounts and trade history</h2><p className="muted">Recording began {date(f.started)}. Each account contains one port-to-port leg and destination business until the next departure. Initial port business is separate. Previous saves have no reconstructed history.</p><p>Opening treasury when recording began: {money(f.openingSilver)} silver. Current treasury: {money(g.silver)} silver.</p><label>Account<select value={scope} onChange={e=>{setScope(e.target.value);setPage(0);}}><option value="all">All recorded activity</option><option value="initial">Initial port business</option>{[...f.voyages].reverse().map(v=><option key={v.id} value={v.id}>#{v.id}: {port(v.from).name} → {port(v.to).name} · {v.status}</option>)}</select></label>{account&&<p>Departed {date(account.departure)}{account.arrival?` · Arrived ${date(account.arrival)}`:''}{account.closed?` · Account ended ${date(account.closed)}`:' · Account remains open'}{account.partial?' · Partial record: tracking began at sea.':''}<br/>Opening silver {money(account.openingSilver)} → {money(account.currentSilver)}</p>}
 <dl className="full-stats"><div><dt>Cash flow</dt><dd>{money(summary.cashFlow)} silver</dd></div><div><dt>Realized cargo margin</dt><dd>{summary.tradingMargin===null?'Unknown costs in sales':`${money(summary.tradingMargin)} silver`}</dd></div><div><dt>Quest and encounter income</dt><dd>{money(summary.otherIncome)} silver</dd></div><div><dt>Cash operating expenses</dt><dd>{money(summary.cashExpenses)} silver</dd></div><div><dt>Recorded consumed/lost cargo cost</dt><dd>{money(summary.usedCost)} silver{summary.unknownCosts?' + unknown costs':''}</dd></div><div><dt>Operating result</dt><dd>{summary.operatingResult===null?'Unknown — incomplete cost records':`${money(summary.operatingResult)} silver`}</dd></div></dl>
 <p className="muted">Purchasing cargo moves cash into inventory; its cost is recognized when sold, consumed or lost. Unsold cargo is not a loss. Preparation fees are included in the prepared food's cost. Ship exchanges are capital cash flow, excluded from operating profit. Starting provisions and legacy goods may have unknown cost; a failed voyage does not automatically write off the ship's value.</p>
 <details><summary>Cash by category</summary><dl className="full-stats">{(Object.keys(ENTRY_NAMES) as EntryKind[]).filter(kind=>entries.some(e=>e.kind===kind&&e.cash!==0)).map(kind=><div key={kind}><dt>{ENTRY_NAMES[kind]}</dt><dd>{money(entries.filter(e=>e.kind===kind).reduce((n,e)=>n+e.cash,0))}</dd></div>)}</dl></details>
 <div className="button-row"><button aria-pressed={view==='ledger'} onClick={()=>{setView('ledger');setPage(0);}}>All entries</button><button aria-pressed={view==='trades'} onClick={()=>{setView('trades');setPage(0);}}>Trade history</button></div><div className="table-wrap"><table><caption>{view==='trades'?'Completed trade lines, grouped by deal number':'Financial ledger'}</caption><thead><tr><th>Date / location</th><th>Entry</th><th>Goods / quantity</th><th>Cash change</th><th>Recorded cost</th></tr></thead><tbody>{history.slice(current*30,current*30+30).map(e=><tr key={e.id}><td>{date(e.hour)}<small>{e.atSea?'At sea':port(e.port).name}</small></td><td>{ENTRY_NAMES[e.kind]}{e.deal&&<small>Deal {e.deal} · {e.channel}</small>}</td><td>{e.good?`${CATALOGUE[e.good].name} · ${e.quantity?.toFixed(2)}`:'—'}</td><td>{money(e.cash)}</td><td>{e.cost===undefined?'—':e.cost===null?'Unknown':money(e.cost)}</td></tr>)}</tbody></table></div>{!history.length&&<p>No entries in this view yet.</p>}<div className="button-row"><button disabled={current===0} onClick={()=>setPage(current-1)}>Newer</button><span>Page {current+1} / {pages}</span><button disabled={current===pages-1} onClick={()=>setPage(current+1)}>Older</button></div></>;
}
