export const CATALOGUE = {
 'provisions': {name:'Provisions',base:1,space:1,weight:.25,category:'Supplies'},
 'medicine': {name:'Medicine',base:40,space:.5,weight:.25,category:'Supplies'},
 'rum': {name:'Rum',base:18,space:1,weight:1.5,category:'Supplies'},
 'planks': {name:'Planks',base:12,space:2,weight:2,category:'Supplies'},
 'sailcloth': {name:'Sailcloth',base:20,space:1,weight:.5,category:'Supplies'},
 'rope': {name:'Rope',base:10,space:1,weight:.75,category:'Supplies'},
 'tools': {name:'Tools',base:30,space:1,weight:2,category:'Supplies'},
 'gunpowder': {name:'Gunpowder',base:24,space:1,weight:1,category:'Supplies'},
 'cannons': {name:'Cannons',base:200,space:5,weight:5,category:'Supplies'},
 'round-shot': {name:'Round Shot',base:8,space:.5,weight:2,category:'Ammunition'},
 'chain-shot': {name:'Chain Shot',base:12,space:.5,weight:2,category:'Ammunition'},
 'grapeshot': {name:'Grapeshot',base:10,space:.5,weight:1.5,category:'Ammunition'},
 'bombs': {name:'Bombs',base:24,space:1,weight:3,category:'Ammunition'},
 'sugar': {name:'Sugar',base:10,space:1,weight:2,category:'Agricultural'},
 'molasses': {name:'Molasses',base:8,space:1,weight:1.5,category:'Agricultural'},
 'coffee': {name:'Coffee',base:28,space:1,weight:.75,category:'Agricultural'},
 'cocoa': {name:'Cocoa',base:24,space:1,weight:.75,category:'Agricultural'},
 'tobacco': {name:'Tobacco',base:32,space:1,weight:.5,category:'Agricultural'},
 'cotton': {name:'Cotton',base:12,space:2,weight:.5,category:'Agricultural'},
 'indigo': {name:'Indigo',base:45,space:.5,weight:.5,category:'Agricultural'},
 'spices': {name:'Spices',base:60,space:.5,weight:.25,category:'Agricultural'},
 'grain': {name:'Grain',base:5,space:1,weight:1,category:'Agricultural'},
 'fruit': {name:'Fruit',base:7,space:1,weight:.75,category:'Agricultural'},
 'salt': {name:'Salt',base:5,space:1,weight:1.5,category:'Preserved food'},
 'salted-fish': {name:'Salted Fish',base:10,space:1,weight:1,category:'Preserved food'},
 'salted-meat': {name:'Salted Meat',base:14,space:1,weight:1.25,category:'Preserved food'},
 'timber': {name:'Timber',base:8,space:3,weight:3,category:'Materials'},
 'iron': {name:'Iron',base:18,space:1,weight:3,category:'Materials'},
 'copper': {name:'Copper',base:30,space:1,weight:3,category:'Materials'},
 'pitch-and-tar': {name:'Pitch and Tar',base:12,space:1,weight:1.5,category:'Materials'},
 'hides': {name:'Hides',base:16,space:2,weight:.75,category:'Materials'},
 'cloth': {name:'Common Cloth',base:24,space:1,weight:.5,category:'Manufactured'},
 'fine-cloth': {name:'Fine Cloth',base:65,space:1,weight:.5,category:'Manufactured'},
 'weapons': {name:'Weapons',base:80,space:1,weight:2,category:'Manufactured'},
 'furniture': {name:'Furniture',base:45,space:4,weight:2,category:'Manufactured'},
 'ceramics': {name:'Ceramics',base:25,space:2,weight:1,category:'Manufactured'},
 'glassware': {name:'Glassware',base:40,space:2,weight:1,category:'Manufactured'},
 'paper': {name:'Paper',base:18,space:1,weight:.5,category:'Manufactured'},
 'books': {name:'Books',base:50,space:1,weight:.75,category:'Manufactured'},
 'wine': {name:'Wine',base:35,space:1,weight:1.5,category:'Luxury'},
 'tea': {name:'Tea',base:55,space:.5,weight:.25,category:'Luxury'},
 'perfume': {name:'Perfume',base:90,space:.25,weight:.25,category:'Luxury'},
 'porcelain': {name:'Porcelain',base:75,space:1,weight:.75,category:'Luxury'},
 'jewelry': {name:'Jewelry',base:300,space:.1,weight:.1,category:'Luxury'},
 'silverware': {name:'Silverware',base:150,space:.5,weight:1,category:'Luxury'},
} as const;
export type GoodId = keyof typeof CATALOGUE;
export const ALL_GOODS = Object.keys(CATALOGUE) as GoodId[];
