import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {act, cash, date, duration, distance, foodFor, wageFor, cargoUsed, passengers, hoursTo, effectiveSpeed, questSkillReward, newGame, offers, port, PORTS, GOODS, SHIP, type Action, type Game, type PortId} from './game';
import {profiles, checkpoints, saveProfile, saveCheckpoint, restoreCheckpoint, type Profile, type Checkpoint} from './storage';
import {loadModels,dressDialogue,type Model} from './nanogpt';
import {Icon,Journal,LogDrawer,type Screen} from './Journal';
import {ModelPicker} from './ModelPicker';
import './themes.css';
import './style.css';
import {THEMES,readTheme,applyTheme,rememberTheme,type ThemeId} from './themes';
const initialTheme=readTheme();
applyTheme(initialTheme);
const PLACES=['Harbour','Store','Tavern','Harbour Master','Shipyard','Church'] as const;
type Place=typeof PLACES[number];
const VOICES:Record<Place,string>={Harbour:'Your ship is ready at anchor. Choose a destination and check your supplies before sailing.',Store:'There is cargo to buy and a fair price for what you bring. Leave room for provisions before you fill your hold.',Tavern:'There are sailors looking for work, and a room if you need rest. Every extra hand needs food and wages.', 'Harbour Master':'I have letters, freight, and passengers awaiting passage. Bring them safely to their destination and report to the harbour office for payment.',Shipyard:'We can repair your ship here. The work takes silver and time; keep your crew provisioned while we work.',Church:'You may record your journey here, Captain. This checkpoint will be yours to return to if the sea takes its toll.'};
function App(){
 const [theme,setTheme]=useState<ThemeId>(initialTheme),[themeNotice,setThemeNotice]=useState('');
 function chooseTheme(id:ThemeId){setTheme(id);applyTheme(id);setThemeNotice(rememberTheme(id)?'Theme saved for this browser.':'Theme applied for this visit. Browser storage is unavailable.');}
 const [all,setAll]=useState<Profile[]>([]),[profile,setProfile]=useState<Profile|null>(null),[place,setPlace]=useState<Place>('Harbour');
 const [cps,setCps]=useState<Checkpoint[]>([]),[name,setName]=useState(''),[cpName,setCpName]=useState('');
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const [screen,setScreen]=useState<Screen>('profiles'),[destination,setDestination]=useState<PortId|null>(null),[quantity,setQuantity]=useState(10);
 const [key,setKey]=useState(''),[model,setModel]=useState(''),[models,setModels]=useState<Model[]>([]),[enabled,setEnabled]=useState(false),[modelBusy,setModelBusy]=useState(false),[modelError,setModelError]=useState('');
 const [dialogue,setDialogue]=useState(''),[dialogueStatus,setDialogueStatus]=useState(''),[cpOpen,setCpOpen]=useState(false);
 const [pendingRestore,setPendingRestore]=useState<Checkpoint|null>(null);
 const lock=useRef(false);
 const g=profile?.game; const current=g?port(g.port):null;
 useEffect(()=>{profiles().then(setAll).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 useEffect(()=>{let cancelled=false;if(profile)checkpoints(profile.id).then(c=>{if(!cancelled)setCps(c);}).catch(e=>setError(e.message));return()=>{cancelled=true;};},[profile?.id]);
 useEffect(()=>{
  setDialogue('');setDialogueStatus('');
  if(screen!=='game'||!g||g.failed||g.voyage||!enabled||!key||!model)return;
  const controller=new AbortController();const timer=setTimeout(()=>{controller.abort();setDialogueStatus('Using the standard dialogue.');},12000);setDialogueStatus('The conversation continues…');
  dressDialogue(key,model,place,port(g.port).name,VOICES[place],controller.signal).then(t=>{if(!controller.signal.aborted){setDialogue(t);setDialogueStatus('AI dialogue · game terms below are authoritative');}}).catch(()=>{if(!controller.signal.aborted)setDialogueStatus('Using the standard dialogue.');}).finally(()=>clearTimeout(timer));
  return()=>{controller.abort();clearTimeout(timer);};
 },[profile?.id,g?.port,place,screen,enabled,key,model,!!g?.failed,!!g?.voyage]);
 async function run(fn:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Something went wrong.');}finally{setBusy(false);lock.current=false;}}
 async function commit(p:Profile){await saveProfile(p);setProfile(p);setAll(old=>[p,...old.filter(x=>x.id!==p.id)]);}
 function perform(a:Action){void run(async()=>{if(!profile)return;const next=act(profile.game,a);await commit({...profile,game:next,updated:Date.now()});setDestination(null);});}
 function openProfile(p:Profile){setProfile(p);setPlace('Harbour');setScreen('game');setDestination(null);setCpOpen(false);setCps([]);setPendingRestore(null);setError('');setNotice('');}
 function create(){void run(async()=>{if(!name.trim())throw new Error('Give your captain a name.');const p={id:crypto.randomUUID(),name:name.trim().slice(0,40),game:newGame(name),updated:Date.now()};await commit(p);setName('');setPlace('Church');setScreen('game');setCpOpen(false);setCps([]);setNotice('Visit the church below to create your first checkpoint.');});}
 function load(c:Checkpoint){if(!profile)return;void run(async()=>{await commit(restoreCheckpoint(profile,c));setPlace('Church');setDestination(null);setCpOpen(false);setPendingRestore(null);setNotice('Church checkpoint restored.');});}
 const checkpointList=<div className="checkpoint-list">{cps.length?cps.map(c=><article className="checkpoint" key={c.id}><div><strong>{c.name}</strong><small>{port(c.game.port).name} · {date(c.game.hours)} · {cash(c.game.silver)} silver</small></div><button disabled={busy} onClick={()=>setPendingRestore(c)}>Restore</button></article>):<p className="muted">No church checkpoints yet. {g?.failed?'Start another captain profile to begin again.':'Visit the church before your first voyage.'}</p>}</div>;
 return <><header className="topbar"><a className="brand" href="#" onClick={e=>{e.preventDefault();if(profile)setScreen('game');}}>⚓ <span>Caribbean Captain<small>A captain’s life, one choice at a time</small></span></a><nav aria-label="Application">{([{id:'game',label:'Gamespace'},{id:'journal',label:'Journal'},{id:'profiles',label:'Captains'},{id:'settings',label:'Settings'}] as const).map(item=><button key={item.id} className={`nav-icon ${screen===item.id?'selected':''}`} title={item.label} aria-label={item.label} aria-current={screen===item.id?'page':undefined} onClick={()=>{setScreen(item.id);setPendingRestore(null);setError('');setNotice('');}} disabled={busy||(!profile&&(item.id==='game'||item.id==='journal'))}><Icon name={item.id}/><span className="nav-tooltip" aria-hidden="true">{item.label}</span></button>)}</nav></header>
 <main className={screen==='game'?'gamespace':undefined}>{pendingRestore&&<section className="alert" role="alertdialog" aria-labelledby="restore-title" aria-describedby="restore-description"><h2 id="restore-title">Restore “{pendingRestore.name}”?</h2><p id="restore-description">Your current progress will be replaced. Other church checkpoints remain available.</p><div className="button-row"><button className="primary" disabled={busy} onClick={()=>load(pendingRestore)}>Confirm restore</button><button disabled={busy} onClick={()=>setPendingRestore(null)}>Keep current progress</button></div></section>}{error&&<div className="alert error" role="alert">{error}</div>}{notice&&<div className="alert" role="status">{notice}</div>}
 {screen==='profiles'&&<section className="welcome"><p className="eyebrow">THE CARIBBEAN · FIRST VOYAGES</p><h1>A ship. A captain.<br/>An open horizon.</h1><p className="lede">Trade between three islands, carry cargo and passengers, and make your silver last until the next harbour.</p><div className="two-columns"><section className="panel"><h2>Begin your command</h2><p>You inherit The Wayfarer, 800 silver, ten sailors, and 120 provisions. Your first stop is the church in Bridgetown.</p><form onSubmit={e=>{e.preventDefault();create();}}><label htmlFor="captain-name">Captain’s name</label><input id="captain-name" maxLength={40} value={name} onChange={e=>setName(e.target.value)} placeholder="Enter a name" required/><button className="primary" disabled={busy||loading}>Create captain</button></form><small>Profiles and checkpoints stay in this browser. There is no game-defined limit; available browser storage applies.</small></section><section className="panel"><h2>Your captains</h2>{loading?<p>Opening the captain’s ledger…</p>:!all.length?<p className="muted">Your first story is waiting to be written.</p>:all.map(p=><button className="profile-row" key={p.id} onClick={()=>openProfile(p)} disabled={busy}><strong>{p.name}</strong><span>{p.game.failed?'Voyage ended':port(p.game.port).name} · {cash(p.game.silver)} silver</span><small>{date(p.game.hours)}</small></button>)}</section></div></section>}
 {screen==='settings'&&<section className="settings panel"><p className="eyebrow">MAKE YOURSELF AT HOME</p><h1>Settings</h1><fieldset className="theme-settings"><legend>Appearance</legend><p>Choose the colours for your captain’s journal. Changes apply immediately and stay with this browser.</p>{(['light','dark'] as const).map(mode=><section key={mode} aria-label={`${mode} themes`}><h2 className="capitalize">{mode} themes</h2><div className="theme-grid">{THEMES.filter(t=>t.mode===mode).map(t=><label className="theme-option" key={t.id}><input type="radio" name="theme" value={t.id} checked={theme===t.id} onChange={()=>chooseTheme(t.id)} aria-label={t.name}/><span className="theme-card" data-theme={t.id}><span className="theme-swatches" aria-hidden="true"><i/><i/><i/><i/></span><strong>{t.name}</strong><small>{t.description}</small></span></label>)}</div></section>)}<small role="status">{themeNotice||`Current theme: ${THEMES.find(t=>t.id===theme)?.name}`}</small></fieldset><p className="eyebrow">OPTIONAL STORYTELLING</p><h2>Dialogue settings</h2><p>The game works without AI. NanoGPT can rephrase the predefined NPC dialogue; prices, actions, and outcomes always come from the game.</p><label htmlFor="api-key">NanoGPT API key</label><input id="api-key" type="password" autoComplete="off" value={key} onChange={e=>{setKey(e.target.value);setEnabled(false);setModels([]);setModel('');}} placeholder="Your personal API key"/><small>The key stays in memory for this tab and is cleared on refresh. Requests go directly to NanoGPT. Enabling dialogue can use your NanoGPT balance.</small><button disabled={modelBusy} onClick={async()=>{setModelBusy(true);setModelError('');try{setModels(await loadModels(key));}catch(e){setModelError(e instanceof Error?e.message:'Unable to load models.');}finally{setModelBusy(false);}}}>{modelBusy?'Loading…':'Load available models'}</button>{modelError&&<p role="alert">{modelError} Standard dialogue is still available.</p>}<ModelPicker models={models} value={model} loading={modelBusy} onChange={id=>{setModel(id);setEnabled(false);}}/><label className="check"><input type="checkbox" checked={enabled} disabled={!key||!model} onChange={e=>setEnabled(e.target.checked)}/>Enable AI dialogue</label><button onClick={()=>{setEnabled(false);setKey('');setModel('');setModels([]);}}>Clear key and disable AI</button></section>}
 {screen==='journal'&&g&&profile&&<Journal key={profile.id} game={g}/>}
 {screen==='game'&&g&&current&&profile&&<>
 <div className="captain-line"><span>CAPTAIN {profile.name.toUpperCase()} · {g.voyage?`At sea → ${port(g.voyage.to).name}`:current.name}</span><span>{date(g.hours)}</span></div>
 <section className="stats quick-stats" aria-label="Ship status"><Stat label="Silver" value={cash(g.silver)} sub={g.silver<0?'Wages owed':'Your treasury'}/><Stat label="Provisions" value={g.provisions.toFixed(1)} sub={`${(g.provisions/(g.crew+passengers(g))).toFixed(1)} days aboard`}/><Stat label="Crew" value={`${g.crew}`} sub={`${passengers(g)} passengers`}/><Stat label="Ship condition" value={`${g.condition}%`} sub={SHIP.name}/><Stat label="Hold" value={`${Math.ceil(cargoUsed(g))} / ${SHIP.capacity}`} sub="Cargo, freight & food"/></section>
 <div className="game-layout"><aside className="port-nav"><p className="eyebrow">{current.island} · {current.nation}</p><h2>{current.name}</h2><nav aria-label="Town locations">{PLACES.map((p,i)=><button key={p} className={place===p?'selected':''} disabled={busy||!!g.failed||!!g.voyage} onClick={()=>{setPlace(p);setDestination(null);setError('');setNotice('');}}><span className="nav-number">0{i+1}</span>{p}<span>›</span></button>)}</nav><div className="ship-note"><strong>{SHIP.name}</strong><p>{SHIP.type}<br/>Speed: {effectiveSpeed(g).toFixed(2)} units/hour<br/>Wages: {g.crew*2} silver/day</p></div><button onClick={()=>setCpOpen(!cpOpen)} disabled={busy}>{cpOpen?'Close checkpoints':'Load checkpoint'} <span className="count">{cps.length}</span></button><small>Progress resumes when you reopen the game. Recovery checkpoints are created only at church.</small></aside>
 <div className="workspace">
 {cpOpen&&<section className="panel"><h2>Church checkpoints</h2>{checkpointList}</section>}
 {g.failed?<section className="panel danger"><p className="eyebrow">THE VOYAGE HAS ENDED</p><h1>A captain’s reckoning</h1><p>{g.failed}</p><h2>Return to a checkpoint</h2>{checkpointList}<button onClick={()=>setScreen('profiles')}>Choose another captain</button></section>:g.voyage?<section className="panel encounter"><p className="eyebrow">AT SEA · EN ROUTE TO {port(g.voyage.to).name.toUpperCase()}</p><h1>Sails on the horizon</h1><p>A pirate ship bears down on The Wayfarer. The distance between you is closing. How will you respond?</p><Roll game={g}/><div className="choices">{(['flee','negotiate','fight'] as const).map(choice=><button disabled={busy} key={choice} onClick={()=>perform({type:'encounter',choice})}><strong>{choice}</strong><small>{choice==='flee'?'Risk damage and delay.':choice==='negotiate'?'Risk a demand for silver.':'Risk ship and crew for a chance at loot.'}</small></button>)}</div><details><summary>2d6 consequences</summary><p>2–6: setback · 7–9: partial success · 10–12: success.</p><p>Flee: 25 / 10 / 0 damage and 24 / 8 / 0 extra hours.<br/>Negotiate: demand of 150 / 60 / 0 silver. An unpaid demand causes 15 damage.<br/>Fight: 50 / 20 / 5 damage, 3 / 1 / 0 crew lost, 0 / 60 / 150 silver earned.</p></details></section>:<section className="panel scene"><p className="eyebrow">{place==='Harbour'?'YOUR NEXT CHAPTER':`${current.name.toUpperCase()} · ${place.toUpperCase()}`}</p><h1>{place==='Harbour'?'Where to, Captain?':place}</h1>{place==='Harbour'&&<p className="scene-description">{current.description}</p>}{place!=='Harbour'&&<blockquote>{dialogue||VOICES[place]}<small>{dialogueStatus||'A word with the '+(place==='Store'?'trader':place==='Tavern'?'tavern keeper':place==='Church'?'church keeper':place==='Shipyard'?'shipwright':'Harbour Master')}</small></blockquote>}
 {place==='Harbour'&&<><div className="routes">{PORTS.filter(p=>p.id!==g.port).map(p=><article className="route" key={p.id}><div><p className="eyebrow">{p.island} · {p.nation}</p><h2>{p.name}</h2><p>{duration(hoursTo(g.port,p.id,g))} in normal weather</p><small>{distance(g.port,p.id).toFixed(1)} distance units · about {Math.ceil(foodFor(g,hoursTo(g.port,p.id,g)))} provisions</small></div><button className="primary" disabled={busy} onClick={()=>setDestination(p.id)}>Plan voyage</button></article>)}</div>{destination&&<div className="departure"><h2>Set sail for {port(destination).name}</h2><p>Expected {duration(hoursTo(g.port,destination,g))}; weather may change this to {duration(Math.ceil(hoursTo(g.port,destination,g)*.85))}–{duration(Math.ceil(hoursTo(g.port,destination,g)*1.25))}.</p><p>Normal-weather cost: {Math.ceil(foodFor(g,hoursTo(g.port,destination,g)))} provisions and {Math.ceil(wageFor(g,hoursTo(g.port,destination,g)))} silver in wages.</p><p className={g.provisions<foodFor(g,Math.ceil(hoursTo(g.port,destination,g)*1.25)+24)?'warning':''}>Suggested reserve, including headwinds and one day of delay: {Math.ceil(foodFor(g,Math.ceil(hoursTo(g.port,destination,g)*1.25)+24))} provisions. You have {g.provisions.toFixed(1)}.</p>{!cps.length&&<p className="warning">You have no checkpoint. Visit the church first; defeat cannot be undone without one.</p>}<p>Every voyage rolls 2d6. A total of 2 brings pirates. Running out of provisions ends the voyage.</p><div className="button-row"><button className="primary" disabled={busy} onClick={()=>perform({type:'sail',to:destination})}>Confirm departure</button><button onClick={()=>setDestination(null)}>Stay in port</button></div></div>}<Roll game={g}/></>}
 {place==='Store'&&<><div className="section-line"><h2>The trading counter</h2><label>Quantity <select aria-label="Trade quantity" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}>{[1,10,25,50].map(n=><option key={n}>{n}</option>)}</select></label></div><p className="muted">Each transaction takes one hour. Prices below are per unit.</p><div className="table-wrap"><table><thead><tr><th>Goods</th><th>Aboard</th><th>Buy / sell</th><th>Trade {quantity}</th></tr></thead><tbody>{GOODS.map(good=><tr key={good}><td className="capitalize">{good}</td><td>{g.cargo[good]}</td><td>{current.prices[good]} / {Math.floor(current.prices[good]*.85)} silver</td><td><div className="button-row"><button disabled={busy} onClick={()=>perform({type:'buy',good,quantity})}>Buy {good}</button><button disabled={busy||g.cargo[good]<quantity} onClick={()=>perform({type:'sell',good,quantity})}>Sell {good}</button></div></td></tr>)}<tr><td>Provisions</td><td>{g.provisions.toFixed(1)}</td><td>1 silver</td><td><button disabled={busy} onClick={()=>perform({type:'buy',good:'provisions',quantity})}>Buy provisions</button></td></tr></tbody></table></div><p className="muted">One person consumes one provision per day, in port or at sea. Passengers eat too.</p></>}
 {place==='Tavern'&&<div className="two-columns"><article className="service"><h2>A hand for the voyage</h2><p>Hire one sailor: 25 silver, 1 hour.</p><p>{g.crew} / {SHIP.maxCrew} crew. Five sailors are needed to sail.</p><button disabled={busy||g.crew===SHIP.maxCrew} onClick={()=>perform({type:'hire'})}>Hire sailor</button></article><article className="service"><h2>A room upstairs</h2><p>Rest for 8 hours: 8 silver.</p><p>Your crew still draws wages and provisions while you rest.</p><button disabled={busy} onClick={()=>perform({type:'sleep'})}>Sleep at tavern</button></article></div>}
 {place==='Shipyard'&&<article className="service"><h2>Repair The Wayfarer</h2><p>Condition: {g.condition}%. Restore it to 100% for {(100-g.condition)*2} silver.</p><p>{g.condition<100?`${Math.ceil((100-g.condition)/5)} hours of work. Wages and provisions continue during repairs.`:'The ship is in excellent condition.'}</p><button className="primary" disabled={busy||g.condition===100} onClick={()=>perform({type:'repair'})}>Repair ship</button></article>}
 {place==='Harbour Master'&&<><div className="section-line"><h2>Your commissions</h2><button disabled={busy||!g.contracts.some(c=>c.to===g.port)} onClick={()=>perform({type:'deliver'})}>Deliver completed tasks</button></div>{g.contracts.length?g.contracts.map(c=><p className="commission" key={c.id}><strong>{c.type}</strong> to {port(c.to).name} · {c.reward} silver {questSkillReward(c)>0?`· +${questSkillReward(c)} Sailing points `:''}{c.to===g.port?'· Ready to deliver':''}</p>):<p className="muted">No active commissions.</p>}<h2>Available work</h2><p className="muted">Up to three active tasks. Acceptance and delivery each take one hour. No deadlines in this first version.</p><div className="contracts">{offers(g).map(c=><article className="contract" key={c.id}><p className="eyebrow">{c.type}</p><h3>{port(c.to).name}</h3><p>{c.type==='Freight'?'40 hold units':c.type==='Passengers'?'3 passenger berths':'No hold space'} · {duration(hoursTo(g.port,c.to,g))}</p><div className="section-line"><strong>{c.reward} silver{questSkillReward(c)>0&&<small>+{questSkillReward(c)} Sailing points</small>}</strong><button disabled={busy||g.contracts.length>=3} onClick={()=>perform({type:'accept',contract:c})}>Accept {c.type.toLowerCase()}</button></div></article>)}</div></>}
 {place==='Church'&&<><h2>Record this chapter</h2><p>Create a free checkpoint of your captain, ship, cargo, contracts, and calendar. You can keep as many as your browser can store.</p><form className="checkpoint-form" onSubmit={e=>{e.preventDefault();void run(async()=>{const c=await saveCheckpoint(profile,cpName||`${current.name} — ${date(g.hours)}`,place);setCps(old=>[c,...old]);setCpName('');setNotice('Checkpoint recorded at church.');});}}><label htmlFor="checkpoint-name">Checkpoint name</label><input id="checkpoint-name" maxLength={60} value={cpName} onChange={e=>setCpName(e.target.value)} placeholder={`${current.name} — before the voyage`}/><button className="primary" disabled={busy}>Create church checkpoint</button></form><h2>Previous chapters</h2>{checkpointList}</>}
 </section>}
 
 </div></div><LogDrawer key={profile.id} game={g}/></>}
 </main><footer>Caribbean Captain <span>First playable edition · Economy values are provisional</span><a href="https://github.com/goodjobwebdev-blip/caribbean-captain">Project & design notes ↗</a></footer></>;
}
function Stat({label,value,sub}:{label:string;value:string;sub:string}){return <div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>;}
function Roll({game}:{game:Game}){if(!game.lastRoll)return null;const r=game.lastRoll;return <div className="roll" aria-label="Last dice roll"><div className="dice" aria-label={`Dice ${r.dice[0]} and ${r.dice[1]}`}><span>{r.dice[0]}</span><span>{r.dice[1]}</span></div><div><strong>{r.dice[0]+r.dice[1]} · {r.outcome}</strong><small className="capitalize">{r.label} · 2d6</small></div></div>;}
createRoot(document.getElementById('root')!).render(<App/>);
