import {useState} from 'react';
import {ALL_GOODS,CATALOGUE,type GoodId} from './goods';
import {PORTS,date,type Game,type PortId} from './game';
import {ensureEconomy,rememberedSale,aboard} from './trade';
import {smuggled,type Channel} from './commerce';
export function MarketsJournal({game}:{game:Game}){
 const [selected,setSelected]=useState<PortId>(game.port),[search,setSearch]=useState(''),[good,setGood]=useState<GoodId>('sugar'),[quantity,setQuantity]=useState(10),[channel,setChannel]=useState<Channel>('legal');
 const g=structuredClone(game);ensureEconomy(g);const memories=channel==='legal'?g.economy!.memories:g.economy!.blackMemories!,snapshot=memories[selected];
 return <><h2>Remembered markets</h2><p className="muted">Only observed prices appear here. Estimates use the recorded stock curve and recorded trading terms. They exclude voyage expenses, future price changes and smuggling penalties.</p>
 <label>Market<select value={channel} onChange={e=>{setChannel(e.target.value as Channel);if(e.target.value==='smuggler')setGood('weapons');}}><option value="legal">Legal markets</option><option value="smuggler">Smugglers</option></select></label>
 <h3>Compare ports</h3><div className="trade-filters"><label>Goods<select value={good} onChange={e=>setGood(e.target.value as GoodId)}>{ALL_GOODS.map(id=><option value={id} key={id}>{CATALOGUE[id].name}</option>)}</select></label><label>Sale quantity<input type="number" min="1" max="200000" step="1" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label></div><p>{aboard(g,good).toFixed(1)} aboard. Profit estimates require a purchase record for the full selected quantity.</p>
 <div className="table-wrap"><table><caption>Remembered prices and hypothetical sale estimates — not guaranteed offers.</caption><thead><tr><th>Port / observation</th><th>Buy / sell per unit</th><th>Estimated sale total</th><th>Estimated cargo profit</th></tr></thead><tbody>{PORTS.map(p=>{const seen=memories[p.id],row=seen?.goods[good],estimate=Number.isSafeInteger(quantity)&&quantity>0?rememberedSale(g,good,p.id,quantity,channel):null;return <tr key={p.id}><th scope="row">{p.name}<small>{seen?`${date(seen.hour)} · ${Math.floor((g.hours-seen.hour)/24)} days ago`:'Not observed'}</small></th><td>{row?`${row.buy.toFixed(2)} / ${row.sell.toFixed(2)}`:'Unknown'}{row?.available===false&&<small>Unavailable at observation</small>}</td><td>{estimate?`${estimate.revenue} silver`:'No usable quote'}</td><td>{estimate?.profit!==null&&estimate?.profit!==undefined?`${estimate.profit.toFixed(2)} silver`:'Unknown'}</td></tr>;})}</tbody></table></div>
 <h3>Port record</h3><div className="trade-filters"><label>Port<select value={selected} onChange={e=>setSelected(e.target.value as PortId)}>{PORTS.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Find goods<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>{!snapshot?<p>You have no market record for this port.</p>:<><p>Recorded {date(snapshot.hour)} · Trade tier {snapshot.tier}</p>{snapshot.event&&<p>Reported event: {snapshot.event.title} · Scheduled end {date(snapshot.event.end)}. This is a historical observation.</p>}<div className="table-wrap"><table><caption>Indicative prices at the time of observation, before quantity effects.</caption><thead><tr><th>Goods</th><th>Role / access</th><th>Stock</th><th>Buy / sell silver</th></tr></thead><tbody>{ALL_GOODS.filter(id=>CATALOGUE[id].name.toLowerCase().includes(search.toLowerCase())&&(channel==='legal'||smuggled(selected,id))).map(id=>{const row=snapshot.goods[id];return <tr key={id}><th scope="row">{CATALOGUE[id].name}</th><td>{row.role} · {row.available===false?'Unavailable':row.controlled?'Controlled':'Open'}</td><td>{Math.floor(row.stock).toLocaleString()}</td><td>{row.buy.toFixed(2)} / {row.sell.toFixed(2)}</td></tr>;})}</tbody></table></div></>}</>;
}
