import {MaterialRepairs} from './SupplyServices';
import {shipPerformance} from './performance';
import {PerformanceBreakdown} from './Performance';
import {useEffect,useRef,useState} from 'react';
import {cash,currentShip,ownedShip,shipPurchaseQuote,type Game,type Action} from './game';
import {SHIPS,BATTERIES,totalCannons,hullRepairQuote,sailRepairQuote,cannonReplacementQuote,shipSaleValue,type ShipClass} from './ships';
export function Shipyard({game:g,busy,perform,view='all'}:{game:Game;busy:boolean;perform:(a:Action)=>void;view?:'all'|'repairs'|'ships'}){
 const ship=ownedShip(g),current=currentShip(g),performance=shipPerformance(g);
 const [tier,setTier]=useState('all'),[shipClass,setShipClass]=useState('all'),[selected,setSelected]=useState<string|null>(null),[confirm,setConfirm]=useState(false);
 const comparison=useRef<HTMLElement>(null);
 useEffect(()=>{if(selected)comparison.current?.focus();},[selected]);
 const choices=SHIPS.filter(s=>(tier==='all'||s.tier===Number(tier))&&(shipClass==='all'||s.shipClass===shipClass));
 const quote=selected?shipPurchaseQuote(g,selected):null;
 const hullCost=hullRepairQuote(ship),sailCost=sailRepairQuote(ship),gunCost=cannonReplacementQuote(ship);
 function filter(setter:(value:string)=>void,value:string){setter(value);setSelected(null);setConfirm(false);}
 return <div className="shipyard">
 {view!=='ships'&&<><article className="service"><p className="eyebrow">YOUR COMMAND · TIER {current.tier} · {current.shipClass.toUpperCase()}</p><h2>{ship.name}</h2><p>{current.label} · sale value <strong>{cash(shipSaleValue(ship))} silver</strong></p><div className="ship-repairs">
 <div><strong>Hull {ship.hullPoints.toFixed(0)} / {current.maxHull}</strong><small>{cash(hullCost)} silver · {Math.ceil((current.maxHull-ship.hullPoints)/5)} hours</small><button disabled={busy||!hullCost||g.silver<hullCost} onClick={()=>perform({type:'repair'})}>Repair hull</button></div>
 <div><strong>Sails {ship.sailCondition}%</strong><small>{cash(sailCost)} silver · {Math.ceil((100-ship.sailCondition)/5)} hours</small><button disabled={busy||!sailCost||g.silver<sailCost} onClick={()=>perform({type:'repair-sails'})}>Repair sails</button></div>
 <div><strong>{totalCannons(ship.cannons)} operational cannons</strong><small>{cash(gunCost)} silver to restore default armament</small><button disabled={busy||!gunCost||g.silver<gunCost} onClick={()=>perform({type:'replace-cannons'})}>Replace lost cannons</button></div>
 </div><small>Wages and provisions continue during repairs. Replacing a cannon takes one hour.</small></article>
 <MaterialRepairs game={g} busy={busy} perform={perform}/><details className="performance-details"><summary>Current ship performance</summary><PerformanceBreakdown game={g}/></details></>}{view!=='repairs'&&<><h2>A new command</h2><p>Buy a fully repaired ship with its default cannons. Your current ship and its cannons are sold in the same exchange. Your people, cargo, provisions, and commissions transfer aboard.</p>
 <div className="ship-filters"><label htmlFor="ship-tier">Tier<select id="ship-tier" value={tier} onChange={e=>filter(setTier,e.target.value)}><option value="all">All tiers</option>{[1,2,3,4,5,6].map(t=><option key={t} value={t}>Tier {t}</option>)}</select></label><label htmlFor="ship-class">Class<select id="ship-class" value={shipClass} onChange={e=>filter(setShipClass,e.target.value)}><option value="all">All classes</option>{(['Merchant','Universal','Warship'] as ShipClass[]).map(c=><option key={c}>{c}</option>)}</select></label><span role="status">{choices.length} configurations</span></div>
 {quote&&<section ref={comparison} tabIndex={-1} className="ship-comparison" aria-labelledby="ship-comparison-title"><div className="section-line"><h2 id="ship-comparison-title">{quote.target.label}</h2><button disabled={busy} onClick={()=>{setSelected(null);setConfirm(false);}}>Close comparison</button></div><p>Tier {quote.target.tier} · {quote.target.shipClass} · {quote.target.hullType} hull</p><div className="table-wrap"><table><caption>Design specifications · current and offered ships</caption><thead><tr><th>Specification</th><th>Current: {current.label}</th><th>Offered: {quote.target.label}</th></tr></thead><tbody>{([
 ['Maximum hull',current.maxHull,quote.target.maxHull],['Base speed (units/hour)',current.speed,quote.target.speed],['Cargo space',current.capacity,quote.target.capacity],['Deadweight capacity',current.deadweight,quote.target.deadweight],['Crew min / optimal / max',`${current.minCrew} / ${current.optimalCrew} / ${current.maxCrew}`,`${quote.target.minCrew} / ${quote.target.optimalCrew} / ${quote.target.maxCrew}`],['Passenger berths',current.passengerCapacity,quote.target.passengerCapacity],['Base maneuverability',current.maneuverability,quote.target.maneuverability],['Hull protection¹',current.protection,quote.target.protection],...BATTERIES.map(b=>[`${b[0].toUpperCase()+b.slice(1)} cannons: default / capacity¹`,`${current.defaultCannons[b]} / ${current.cannonCapacity[b]}`,`${quote.target.defaultCannons[b]} / ${quote.target.cannonCapacity[b]}`])
 ] as (string|number)[][]).map(([label,a,b])=><tr key={label}><th scope="row">{label}</th><td>{a}</td><td>{b}</td></tr>)}</tbody></table></div><p className="muted">¹ Cannon layouts and protection are reserved for future battle rules. Installed cannons contribute weight. Ship tier and class do not add hidden bonuses.</p>
 <h3>With your people and cargo aboard</h3><p className="muted">Your current ship keeps its present condition and cannons in this comparison. The offered ship is fully repaired and carries its default cannons. Your Sailing mastery applies to both.</p><div className="table-wrap"><table><thead><tr><th>Current performance</th><th>Your ship</th><th>Offered ship</th></tr></thead><tbody><tr><th>Loaded speed</th><td>{performance.speed.toFixed(2)} units/hour</td><td>{quote.offeredPerformance.speed.toFixed(2)} units/hour</td></tr><tr><th>Loaded maneuverability</th><td>{performance.maneuverability.toFixed(1)}</td><td>{quote.offeredPerformance.maneuverability.toFixed(1)}</td></tr><tr><th>Weight / capacity</th><td>{performance.weight.total.toFixed(1)} / {current.deadweight}</td><td>{quote.offeredPerformance.weight.total.toFixed(1)} / {quote.target.deadweight}</td></tr><tr><th>Crew effectiveness</th><td>{(performance.factors.crew*100).toFixed(1)}%</td><td>{(quote.offeredPerformance.factors.crew*100).toFixed(1)}%</td></tr></tbody></table></div><dl className="ship-price"><div><dt>Full purchase price</dt><dd>{cash(quote.target.price)} silver</dd></div><div><dt>Current ship sale value</dt><dd>−{cash(quote.sale)} silver</dd></div><div><dt>{quote.balance>=0?'Balance to pay':'Silver you receive'}</dt><dd>{cash(Math.abs(quote.balance))} silver</dd></div><div><dt>Treasury after exchange</dt><dd>{cash(g.silver-quote.balance)} silver</dd></div></dl>
 <p>With your {g.crew} sailors: {g.crew*2} silver/day in wages. At the offered ship’s optimal crew: {quote.target.optimalCrew*2} silver/day and {quote.target.optimalCrew} provisions/day, plus passengers. Extra sailors must be hired separately.</p>
 {quote.problems.length>0&&<ul className="warning">{quote.problems.map(p=><li key={p}>{p}</li>)}</ul>}
 {confirm?<div className="exchange-confirm" role="group" aria-label="Confirm ship exchange"><p><strong>Sell {ship.name} and take command of {quote.target.label}?</strong> You can recover the previous ship only by buying it again or restoring a church checkpoint.</p><div className="button-row"><button className="primary" disabled={busy||!!quote.problems.length} onClick={()=>{perform({type:'buy-ship',configurationId:quote.target.id});setConfirm(false);}}>Confirm exchange</button><button disabled={busy} onClick={()=>setConfirm(false)}>Cancel</button></div></div>:<button className="primary" disabled={busy||!!quote.problems.length} onClick={()=>setConfirm(true)}>Review exchange</button>}
 </section>}
 <div className="ship-catalogue">{choices.map(s=>{const q=shipPurchaseQuote(g,s.id),owned=s.id===current.id;return <article className={`ship-card ${selected===s.id?'is-selected':''}`} key={s.id}><p className="eyebrow">TIER {s.tier} · {s.shipClass.toUpperCase()}</p><h3>{s.label}</h3><p>{s.speed.toFixed(2)} base speed · {s.capacity} cargo space<br/>{s.minCrew}–{s.maxCrew} crew · {s.passengerCapacity} berths</p><strong>{cash(s.price)} silver</strong><small>{owned?'Your current configuration':`${q.balance>=0?'After selling yours:':'Receive after exchange:'} ${cash(Math.abs(q.balance))} silver`}</small><button aria-pressed={selected===s.id} disabled={busy||owned} onClick={()=>{setSelected(s.id);setConfirm(false);}}>{owned?'Current ship':`Compare ${s.label}`}</button></article>;})}</div>
 </>}
 </div>;
}
