import {StatusMeter} from './GameDetails';
import type {Game} from './game';
import {effectiveSpeed,sailingBonus} from './game';
import {spread} from './trade';
import {nextTierRequirement,PLAYER_SKILLS,type PlayerSkill} from './skills';

type SkillDefinition={
 id:PlayerSkill;
 name:string;
 category:string;
 description:string;
 currentMechanic:string;
 futureMechanic:string;
 currentQuests:string;
 currentActions:string;
 plannedActions:string;
};

const noQuest='No quest currently awards points for this skill.';
export const SKILL_DEFINITIONS:SkillDefinition[]=[
 {id:'sailing',name:'Sailing & Navigation',category:'Sailing and awareness',description:'Ship handling, sail and rigging work, route planning, weather judgment, and avoiding maritime hazards.',currentMechanic:'Each tier adds 5% ship speed and reduces the time cost of sailing orders in naval combat. Sailing mastery also helps pursuit, escape, and avoidance checks.',futureMechanic:'Weather judgment, maritime hazard checks, route planning, and ship-tier training limits.',currentQuests:'Letter delivery commissions award points based on route distance.',currentActions:'Arrive after a voyage: 1 point per 24 actual sailing hours, with leftover hours carried forward.',plannedActions:'Advanced navigation, difficult-weather voyages, and maritime hazard challenges.'},
 {id:'lookout',name:'Lookout',category:'Sailing and awareness',description:'Spotting ships, reefs, land, threats, opportunities, people, objects, and suspicious activity at sea or ashore.',currentMechanic:'Improves early-sighting movement checks, resists enemy combat deception, and reveals captain rank and hull condition at tier 3.',futureMechanic:'Reef, land, opportunity, object, and suspicious-activity detection on voyages and ashore.',currentQuests:noQuest,currentActions:'Investigate an early ship sighting: 0.5 point.',plannedActions:'Keep watch, survey coasts, identify hazards, and investigate hidden opportunities.'},
 {id:'aiming',name:'Cannon Aiming',category:'Naval combat',description:'Cannon accuracy and effective firing range.',currentMechanic:'Improves cannon-volley rolls and reduces the time cost of firing orders.',futureMechanic:'Called shots, range mastery, battery specializations, and advanced ammunition control.',currentQuests:noQuest,currentActions:'Fire a valid cannon volley: 0.25 point on a setback, 0.5 otherwise.',plannedActions:'Gunnery drills, difficult-range shots, and precision fire challenges.'},
 {id:'reloading',name:'Cannon Reloading',category:'Naval combat',description:'Reload speed, safe powder handling, and recovery from misfires.',currentMechanic:'Reduces the time cost of reload and unload orders.',futureMechanic:'Misfire recovery, powder-safety checks, and specialized reload procedures.',currentQuests:noQuest,currentActions:'Complete a timed cannon reload: 0.5 point.',plannedActions:'Port gunnery drills, emergency reloads, and powder-handling challenges.'},
 {id:'navalTactics',name:'Naval Tactics',category:'Naval combat',description:'Combat positioning, pursuit, escape, broadside tactics, and using wind, terrain, and the environment.',currentMechanic:'Not implemented yet.',futureMechanic:'Positioning advantages, pursuit and escape decisions, broadside coordination, and environmental tactics.',currentQuests:noQuest,currentActions:'No action currently awards points for this skill.',plannedActions:'Win positional advantages, execute tactical maneuvers, and resolve naval-command challenges.'},
 {id:'boarding',name:'Boarding',category:'Naval combat',description:'Initiating and defending boarding actions and gaining an advantage during boarding.',currentMechanic:'Adds 5% boarding strength per tier and reduces the time cost of grappling orders.',futureMechanic:'Boarding defense, specialized assaults, boarding equipment, and command options.',currentQuests:noQuest,currentActions:'Resolve a grappling roll or deck-battle round: 0.25 point on a setback, 0.5 otherwise.',plannedActions:'Repel boarders, lead specialized assaults, and complete boarding objectives.'},
 {id:'demolitions',name:'Demolitions',category:'Naval combat',description:'Explosives, gunpowder traps, sabotage, fire control, and fire ships.',currentMechanic:'Reduces the time cost of deploying explosives and improves a gunpowder distraction used while fleeing.',futureMechanic:'Sabotage, traps, controlled fires, fire ships, and explosive damage handling.',currentQuests:noQuest,currentActions:'Flee using a gunpowder charge or deploy a powder charge in battle: 0.5 point.',plannedActions:'Disarm explosives, sabotage targets, prepare traps, and control shipboard fires.'},
 {id:'leadership',name:'Leadership',category:'Command and crew',description:'Recruiting crew, maintaining morale and loyalty, managing discipline, and improving crew effectiveness.',currentMechanic:'Improves battle morale checks and reduces the time cost of rallying the crew or extinguishing fire.',futureMechanic:'Recruitment, loyalty, discipline, desertion, mutiny, officers, and broader crew effectiveness.',currentQuests:noQuest,currentActions:'Successfully reduce crew shock or shipboard fire in battle: 0.5 point.',plannedActions:'Resolve crew disputes, inspire the company, recruit specialists, and manage crises.'},
 {id:'training',name:'Training',category:'Command and crew',description:'Training crew members, improving crew capabilities, and reducing operational mistakes.',currentMechanic:'Each tier increases the experience gained by the crew during paid training sessions.',futureMechanic:'Training plans, officer instruction, reduced mistakes, and advanced crew specializations.',currentQuests:noQuest,currentActions:'Complete a paid crew training session at the tavern: 0.5 point.',plannedActions:'Run drills at sea, mentor officers, and complete specialist training programs.'},
 {id:'carpentry',name:'Carpentry',category:'Ship maintenance and medicine',description:'Repairing hulls and masts and restoring structural damage.',currentMechanic:'Improves hull restored by patching, and reduces the time cost of hull repair and flooding-control orders.',futureMechanic:'Port repairs, mast work, preventative maintenance, and emergency structural checks.',currentQuests:noQuest,currentActions:'Restore hull or reduce flooding during battle: 0.5 point.',plannedActions:'Repair storm damage, maintain the ship, salvage timber, and complete dockyard work.'},
 {id:'sailmaking',name:'Sailmaking',category:'Ship maintenance and medicine',description:'Repairing sails, ropes, and rigging.',currentMechanic:'Improves sail condition restored and reduces the time cost of sail-repair orders.',futureMechanic:'Rigging replacement, preventative maintenance, sail plans, and storm-damage repair.',currentQuests:noQuest,currentActions:'Restore sail condition during battle: 0.5 point.',plannedActions:'Mend sails at sea, repair storm damage, and complete rigging work.'},
 {id:'doctoring',name:'Doctoring',category:'Ship maintenance and medicine',description:'Treating wounds and illness and caring for injured crew members.',currentMechanic:'Improves injured crew restored during battle and healed by professional medical care; reduces battle treatment time.',futureMechanic:'Disease, medicine quality, surgery, long-term injuries, and preventative care.',currentQuests:noQuest,currentActions:'Restore injured crew during battle: 0.5 point. Professional medical care uses mastery but grants no points.',plannedActions:'Treat illness, perform difficult surgery, gather remedies, and manage outbreaks.'},
 {id:'logistics',name:'Logistics',category:'Ship maintenance and medicine',description:'Managing food, supplies, ammunition, cargo capacity, and resource efficiency.',currentMechanic:'Not implemented yet.',futureMechanic:'Supply efficiency, spoilage, ammunition handling, cargo planning, and voyage provisioning.',currentQuests:noQuest,currentActions:'No action currently awards points for this skill.',plannedActions:'Provision voyages, prevent spoilage, optimize cargo, and resolve supply shortages.'},
 {id:'trade',name:'Trade',category:'Social and economic',description:'Negotiating prices, evaluating goods, and identifying profitable deals.',currentMechanic:'Each tier improves both buying and selling prices by reducing the market spread.',futureMechanic:'Appraisal, advanced negotiations, market opportunities, and merchant specializations.',currentQuests:noQuest,currentActions:'Earn 1 point per 100 silver of profitable resale from goods bought at another port; fractions carry forward.',plannedActions:'Appraise unusual cargo, negotiate special deals, and complete merchant challenges.'},
 {id:'diplomacy',name:'Diplomacy',category:'Social and economic',description:'Building relationships, negotiating agreements, requesting favors, and reaching peaceful resolutions.',currentMechanic:'Improves negotiation checks during ship encounters.',futureMechanic:'Faction agreements, favors, reputation recovery, mediation, and political access.',currentQuests:noQuest,currentActions:'Resolve an encounter negotiation: 0.25 point on a setback, 0.5 otherwise.',plannedActions:'Broker agreements, request favors, mediate disputes, and represent factions.'},
 {id:'deception',name:'Deception',category:'Social and economic',description:'Lying, disguises, false flags, forgery, and misleading other characters.',currentMechanic:'Improves encounter and combat deception, helps conceal hostile attacks, and reduces combat-deception time.',futureMechanic:'Disguises, forgery, smuggling cover stories, infiltration, and identity concealment.',currentQuests:noQuest,currentActions:'Resolve encounter or combat deception: 0.25 point on a setback, 0.5 otherwise.',plannedActions:'Use disguises, forge documents, maintain false identities, and misdirect pursuers.'},
 {id:'intimidation',name:'Intimidation',category:'Social and economic',description:'Threats, coercion, interrogation, and forcing surrender.',currentMechanic:'Improves threat checks in encounters and surrender demands during captain duels.',futureMechanic:'Interrogation, coercive bargaining, reputation effects, and crew intimidation.',currentQuests:noQuest,currentActions:'Resolve an encounter threat or duel surrender demand: 0.25 point on a setback, 0.5 otherwise.',plannedActions:'Interrogate captives, pressure rivals, and force non-combat resolutions.'},
 {id:'lightWeapons',name:'Light Weapons',category:'Personal combat and movement',description:'Knives, rapiers, and other fast personal weapons.',currentMechanic:'Improves duel attacks and weapon defenses when using a light weapon.',futureMechanic:'Weapon techniques, speed advantages, counters, and light-weapon perks.',currentQuests:noQuest,currentActions:'Roll a duel attack or weapon defense with a light weapon: 0.25 point on a setback, 0.5 otherwise.',plannedActions:'Spar, train with masters, and win light-weapon challenges.'},
 {id:'mediumWeapons',name:'Medium Weapons',category:'Personal combat and movement',description:'Sabres, cutlasses, axes, clubs, and other balanced weapons.',currentMechanic:'Improves duel attacks and weapon defenses when using a medium weapon.',futureMechanic:'Weapon techniques, balanced stances, counters, and medium-weapon perks.',currentQuests:noQuest,currentActions:'Roll a duel attack or weapon defense with a medium weapon: 0.25 point on a setback, 0.5 otherwise.',plannedActions:'Spar, train with masters, and win medium-weapon challenges.'},
 {id:'heavyWeapons',name:'Heavy Weapons',category:'Personal combat and movement',description:'Two-handed blades, heavy axes, and crushing weapons.',currentMechanic:'Improves duel attacks and weapon defenses when using a heavy weapon.',futureMechanic:'Power attacks, armor breaking, heavy counters, and heavy-weapon perks.',currentQuests:noQuest,currentActions:'Roll a duel attack or weapon defense with a heavy weapon: 0.25 point on a setback, 0.5 otherwise.',plannedActions:'Spar, train with masters, and win heavy-weapon challenges.'},
 {id:'shooting',name:'Shooting',category:'Personal combat and movement',description:'Pistols, muskets, and other personal firearms.',currentMechanic:'Improves pistol attacks in captain duels.',futureMechanic:'Muskets, aimed shots, firearm quality, range, and shooting perks.',currentQuests:noQuest,currentActions:'Roll a pistol attack during a duel: 0.25 point on a setback, 0.5 otherwise.',plannedActions:'Practice at ranges, hunt, and complete marksmanship challenges.'},
 {id:'athletics',name:'Athletics',category:'Personal combat and movement',description:'Climbing, swimming, jumping, physical endurance, and resisting exhaustion.',currentMechanic:'Improves dodge defenses during captain duels.',futureMechanic:'Climbing, swimming, jumping, endurance checks, and fatigue resistance.',currentQuests:noQuest,currentActions:'Roll a dodge defense during a duel: 0.25 point on a setback, 0.5 otherwise.',plannedActions:'Climb rigging, swim, cross hazards, train endurance, and escape on foot.'},
 {id:'stealth',name:'Stealth',category:'Adventuring',description:'Sneaking, hiding, pickpocketing, lockpicking, and bypassing security unnoticed.',currentMechanic:'Not implemented yet.',futureMechanic:'Infiltration, concealment, pickpocketing, lockpicking, and security bypass.',currentQuests:noQuest,currentActions:'No action currently awards points for this skill.',plannedActions:'Sneak through guarded areas, pick locks, hide contraband, and conduct covert work.'},
 {id:'luck',name:'Luck',category:'Adventuring',description:'Fortunate outcomes, rare events, unexpected discoveries, and other chance-based effects.',currentMechanic:'Not implemented yet.',futureMechanic:'Rare-event chances, fortunate discoveries, limited rerolls, and favorable random outcomes.',currentQuests:noQuest,currentActions:'No action currently awards points for this skill.',plannedActions:'Survive improbable events, find rare discoveries, and resolve chance-driven opportunities.'}
];

if(SKILL_DEFINITIONS.length!==PLAYER_SKILLS.length)throw Error('Every player skill needs a card definition.');

function Status({children}:{children:string}){return <span className="skill-status">{children}</span>;}
function SkillCard({definition:d,game:g}:{definition:SkillDefinition;game:Game}){
 const progress=g.skills?.[d.id]??{tier:0,points:0};
 const target=nextTierRequirement(progress.tier);
 const mechanic=d.id==='sailing'?`${d.currentMechanic} Current bonus: +${Math.round(sailingBonus(g)*100)}%; effective speed: ${effectiveSpeed(g).toFixed(2)} units/hour.`:d.id==='trade'?`${d.currentMechanic} Current market spread: ${(spread(g)*100).toFixed(1)}%.`:d.currentMechanic;
 return <article className="skill-card" data-skill={d.id}>
  <div className="section-line"><div><p className="skill-category">{d.category}</p><h2>{d.name}</h2></div><span className="quest-status">Tier {progress.tier} / 10</span></div>
  <p>{d.description}</p>
  <dl className="full-stats skill-progress-stats"><div><dt>Mastery tier</dt><dd>{progress.tier} / 10</dd></div><div><dt>Progress to next tier</dt><dd>{target===null?'Maximum mastery':`${progress.points.toFixed(2)} / ${target} points`}</dd></div>{d.id==='sailing'&&<div><dt>Practice toward next point</dt><dd>{target===null?'Maximum mastery':`${progress.sailingHours??0} / 24 sailing hours`}</dd></div>}</dl>
  <StatusMeter label={target===null?`${d.name} mastery`:`${d.name} progress toward tier ${progress.tier+1}`} value={target===null?1:progress.points} max={target??1} detail={target===null?'Maximum mastery':`${progress.points.toFixed(2)} / ${target} points · ${(target-progress.points).toFixed(2)} to next tier`} progress/>
  <div className="skill-information">
   <section><h3>Influences now</h3><p>{mechanic}</p></section>
   <section><h3>Future influence <Status>TBD</Status></h3><p>{d.futureMechanic}</p></section>
   <section><h3>Quests now</h3><p>{d.currentQuests}</p></section>
   <section><h3>Planned quests <Status>QUEST TBD</Status></h3><p>Quest name, story, requirements, and skill-point reward are still to be designed.</p></section>
   <section><h3>Books <Status>TBD</Status></h3><p>Books are not implemented. Book names, rarity, required level, and skill-point rewards are still to be designed.</p></section>
   <section><h3>Actions that award points now</h3><p>{d.currentActions}</p></section>
   <section><h3>Planned point-earning actions <Status>TBD</Status></h3><p>{d.plannedActions}</p></section>
  </div>
 </article>;
}

export function SkillCards({game}:{game:Game}){
 return <><p className="eyebrow">PLAYER SKILLS</p><p className="muted">Only mastery tiers affect gameplay. Points track progress toward the next tier. Planned content is marked TBD and does not affect the current game.</p><div className="skill-card-list">{SKILL_DEFINITIONS.map(d=><SkillCard key={d.id} definition={d} game={game}/>)}</div></>;
}
