import {FoodPreparation} from './SupplyServices';
import {accessProblem,eventFactor,localEvent,smuggled,smugglerOpen,type Channel} from './commerce';
import {useState,useEffect} from 'react';
import {ALL_GOODS,CATALOGUE,type GoodId} from './goods';
import {aboard,marketRule,stockAt,spread,reference,quoteBasket,cargoCost,type BasketLine} from './trade';
import {currentShip,date,type Game,type Action} from './game';
export function Store({game:g,busy,perform,dialogueChannel}:{game:Game;busy:boolean;perform:(action:Action)=>void;dialogueChannel?:Channel}){
 const [lines,setLines]=useState<BasketLine[]>([]),[search,setSearch]=useState(''),[category,setCategory]=useState('All'),[aboardOnly,setAboardOnly]=useState(false),[channel,setChannel]=useState<Channel>(dialogueChannel??'legal');
 useEffect(()=>{setLines([]);},[g]);
 const quote=quoteBasket(g,lines,channel),spec=currentShip(g),event=localEvent(g),closed=channel==='smuggler'&&(!g.economy?.commerce?.contacts[g.port]||!smugglerOpen(g));
 function edit(good:GoodId,side:'buy'|'sell',quantity:number){setLines(old=>[...old.filter(l=>l.good!==good),...(quantity>0?[{good,side,quantity}]:[])]);}
 function sellAll(id:GoodId){
  const reserve=id==='provisions'?(g.crew+g.contracts.filter(c=>c.type==='Passengers').reduce((n,c)=>n+c.amount,0))/24:0;
  edit(id,'sell',Math.max(0,Math.floor(Math.min(aboard(g,id)-reserve,marketRule(g.port,id,channel).max-stockAt(g,id,g.port,channel)))));
 }
 return <><h2>The trading counter</h2>{g.lastRoll?.label==='Smuggling inspection'&&<p role="status" className="alert"><strong>Most recent inspection: {g.lastRoll.dice.join(' + ')} · {g.lastRoll.outcome}</strong><br/>{g.log.find(entry=>entry.text.startsWith('Smuggling inspection:'))?.text}</p>}{!dialogueChannel&&<div className="button-row" aria-label="Market"><button aria-pressed={channel==='legal'} disabled={busy} onClick={()=>{setChannel('legal');setLines([]);}}>Legal market</button><button aria-pressed={channel==='smuggler'} disabled={busy} onClick={()=>{setChannel('smuggler');setLines([]);}}>Smugglers</button></div>}{event&&<p className="market-event"><strong>{event.title}</strong> · {event.category} prices ×{event.multiplier} · Ends {date(event.end)}</p>}{channel==='smuggler'&&<div className="alert"><strong>Every confirmed deal triggers a 2d6 inspection.</strong><p>2–6: all purchases in this deal confiscated, a fine of 25% of gross trade (minimum 50), local attitude −10, reputation −5. 7–9: a 10% fine (minimum 25), attitude −3, reputation −1. 10–12: undetected. Fines can leave debt. Sold goods remain sold; sale proceeds are subject to the fine.</p></div>}{closed&&<p className="warning">{g.economy?.commerce?.contacts[g.port]?'Your contact is absent today. Return tomorrow.':'Ask for a contact at the tavern first.'}</p>}<p className="muted">Build one basket of purchases and sales. The complete deal takes one hour. Larger quantities change the price as stock changes.</p>
 <div className="trade-filters"><label>Find goods<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name of goods"/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{['All',...new Set(ALL_GOODS.map(id=>CATALOGUE[id].category))].map(c=><option key={c}>{c}</option>)}</select></label><label className="check-label"><input type="checkbox" checked={aboardOnly} onChange={e=>setAboardOnly(e.target.checked)}/>Aboard only</label></div>
 {!closed&&<p className="muted trade-scroll-hint" id="trade-scroll-hint">Swipe the goods table sideways to see prices and deal controls.</p>}
 {!closed&&<div className="table-wrap trade-table" role="region" aria-label="Goods and trading controls" tabIndex={0}><table><caption>Indicative silver per unit; exact totals appear in your basket.</caption><thead><tr><th>Goods / market</th><th>Stock / aboard</th><th>Buy / sell</th><th>Space / weight</th><th>Your deal</th></tr></thead><tbody>{ALL_GOODS.filter(id=>CATALOGUE[id].name.toLowerCase().includes(search.toLowerCase())&&(category==='All'||CATALOGUE[id].category===category)&&(!aboardOnly||aboard(g,id)>0)&&(channel==='legal'||smuggled(g.port,id))).map(id=>{const item=CATALOGUE[id],r=marketRule(g.port,id,channel),stock=stockAt(g,id,g.port,channel),price=r.factor*eventFactor(g,id)*reference(stock,r.target),restriction=accessProblem(g,id,channel),line=lines.find(l=>l.good===id);return <tr key={id}><th scope="row">{item.name}<small>{r.role}{r.controlled?' · Controlled':''}{id==='fruit'?' · Spoils 5%/day':''}</small></th><td>{Math.floor(stock).toLocaleString()} / {aboard(g,id).toFixed(1)}</td><td>{(price*(1+spread(g,channel))).toFixed(2)} / {(price*(1-spread(g,channel))).toFixed(2)}</td><td>{item.space} / {item.weight}</td><td>{restriction?<small>{restriction}</small>:<div><div className="trade-entry"><select aria-label={`${item.name} buy or sell`} disabled={busy} value={line?.side??'buy'} onChange={e=>edit(id,e.target.value as 'buy'|'sell',line?.quantity??1)}><option value="buy">Buy</option><option value="sell">Sell</option></select><input aria-label={`${item.name} quantity`} disabled={busy} type="number" min="0" max="200000" step="1" value={line?.quantity??0} onChange={e=>edit(id,line?.side??'buy',Number(e.target.value))}/></div><div className="quantity-shortcuts" aria-label={`${item.name} quantity shortcuts`}>{[1,10,50].map(q=><button key={q} disabled={busy} onClick={()=>edit(id,line?.side??'buy',q)}>{q}</button>)}<button disabled={busy||aboard(g,id)<1} onClick={()=>sellAll(id)}>Sell all</button></div></div>}</td></tr>;})}</tbody></table></div>}
 <section className="basket" aria-label="Trade basket"><h2>Your basket</h2>{lines.length?<><ul>{quote.lines.map(l=><li key={l.good}><span>{l.side==='buy'?'Buy':'Sell'} {l.quantity} {CATALOGUE[l.good].name} · <strong>{l.total} silver</strong>{l.side==='sell'&&<small>{cargoCost(g,l.good,l.quantity).unknown>1e-8?'Profit unknown: some cargo has no purchase record':`Estimated cargo profit: ${(l.total-cargoCost(g,l.good,l.quantity).total).toFixed(2)} silver before wages, food and any fine`}</small>}</span><button disabled={busy} aria-label={`Remove ${CATALOGUE[l.good].name}`} onClick={()=>setLines(lines.filter(x=>x.good!==l.good))}>Remove</button></li>)}</ul><dl className="full-stats"><div><dt>Purchases / sales</dt><dd>{quote.buys} / {quote.sales} silver</dd></div><div><dt>{channel==='smuggler'?'Silver before any inspection fine':'Silver after deal and hourly wages'}</dt><dd>{quote.finalSilver.toFixed(2)}</dd></div><div><dt>Hold after exchange</dt><dd>{quote.space.toFixed(1)} / {spec.capacity}</dd></div><div><dt>Weight after exchange</dt><dd>{quote.weight.toFixed(1)} / {spec.deadweight}</dd></div>{channel==='smuggler'&&<div><dt>Silver if caught / fined</dt><dd>{(quote.finalSilver-Math.max(50,Math.ceil((quote.buys+quote.sales)*.25))).toFixed(2)} / {(quote.finalSilver-Math.max(25,Math.ceil((quote.buys+quote.sales)*.1))).toFixed(2)}</dd></div>}<div><dt>Trade learning</dt><dd>+{quote.xp.toFixed(2)} points</dd></div></dl><p className="muted">The crew also eats one hour’s provisions. Keep enough food for your next voyage.</p>{quote.errors.length>0&&<ul className="warning" aria-live="polite">{quote.errors.map((e,i)=><li key={i}>{e}</li>)}</ul>}<div className="button-row"><button className="primary" disabled={busy||closed||quote.errors.length>0} onClick={()=>perform({type:'trade',lines,expected:quote.token,channel})}>{channel==='smuggler'?'Confirm risky deal':'Confirm deal'} · 1 hour</button><button disabled={busy} onClick={()=>setLines([])}>Clear basket</button></div></>:<p className="muted">Set quantities above to add goods. Sales can fund purchases and free space in the same deal.</p>}</section>{!dialogueChannel&&<FoodPreparation game={g} busy={busy} perform={perform}/>}<p className="muted">One person consumes one provision per day, in port or at sea. National permits are available at the Harbour Master. You can supply repair materials at the shipyard. Prepare cannon ammunition and powder before departure.</p></>;
}
