import {useState} from 'react';
import {ALL_GOODS,CATALOGUE,type GoodId} from './goods';
import {aboard,marketRule,stockAt,spread,reference,quoteBasket,type BasketLine} from './trade';
import {currentShip,type Game,type Action} from './game';
export function Store({game:g,busy,perform}:{game:Game;busy:boolean;perform:(action:Action)=>void}){
 const [lines,setLines]=useState<BasketLine[]>([]),[search,setSearch]=useState(''),[category,setCategory]=useState('All');
 const quote=quoteBasket(g,lines),spec=currentShip(g);
 function edit(good:GoodId,side:'buy'|'sell',quantity:number){setLines(old=>[...old.filter(l=>l.good!==good),...(quantity>0?[{good,side,quantity}]:[])]);}
 return <><h2>The trading counter</h2><p className="muted">Build one basket of purchases and sales. The complete deal takes one hour. Larger quantities change the price as stock changes.</p>
 <div className="trade-filters"><label>Find goods<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name of goods"/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{['All',...new Set(ALL_GOODS.map(id=>CATALOGUE[id].category))].map(c=><option key={c}>{c}</option>)}</select></label></div>
 <div className="table-wrap"><table><caption>Indicative silver per unit; exact totals appear in your basket.</caption><thead><tr><th>Goods / market</th><th>Stock / aboard</th><th>Buy / sell</th><th>Space / weight</th><th>Your deal</th></tr></thead><tbody>{ALL_GOODS.filter(id=>CATALOGUE[id].name.toLowerCase().includes(search.toLowerCase())&&(category==='All'||CATALOGUE[id].category===category)).map(id=>{const item=CATALOGUE[id],r=marketRule(g.port,id),stock=stockAt(g,id),price=r.factor*reference(stock,r.target),line=lines.find(l=>l.good===id);return <tr key={id}><th scope="row">{item.name}<small>{r.role}{r.controlled?' · Controlled':''}</small></th><td>{Math.floor(stock).toLocaleString()} / {aboard(g,id).toFixed(1)}</td><td>{(price*(1+spread(g))).toFixed(2)} / {(price*(1-spread(g))).toFixed(2)}</td><td>{item.space} / {item.weight}</td><td>{r.controlled?<small>Access unavailable</small>:<div className="trade-entry"><select aria-label={`${item.name} buy or sell`} disabled={busy} value={line?.side??'buy'} onChange={e=>edit(id,e.target.value as 'buy'|'sell',line?.quantity??1)}><option value="buy">Buy</option><option value="sell">Sell</option></select><input aria-label={`${item.name} quantity`} disabled={busy} type="number" min="0" max="200000" step="1" value={line?.quantity??0} onChange={e=>edit(id,line?.side??'buy',Number(e.target.value))}/></div>}</td></tr>;})}</tbody></table></div>
 <section className="basket" aria-label="Trade basket"><h2>Your basket</h2>{lines.length?<><ul>{quote.lines.map(l=><li key={l.good}><span>{l.side==='buy'?'Buy':'Sell'} {l.quantity} {CATALOGUE[l.good].name} · <strong>{l.total} silver</strong></span><button disabled={busy} aria-label={`Remove ${CATALOGUE[l.good].name}`} onClick={()=>setLines(lines.filter(x=>x.good!==l.good))}>Remove</button></li>)}</ul><dl className="full-stats"><div><dt>Purchases / sales</dt><dd>{quote.buys} / {quote.sales} silver</dd></div><div><dt>Silver after deal and hourly wages</dt><dd>{quote.finalSilver.toFixed(2)}</dd></div><div><dt>Hold after exchange</dt><dd>{quote.space.toFixed(1)} / {spec.capacity}</dd></div><div><dt>Weight after exchange</dt><dd>{quote.weight.toFixed(1)} / {spec.deadweight}</dd></div><div><dt>Trade learning</dt><dd>+{quote.xp.toFixed(2)} points</dd></div></dl><p className="muted">The crew also eats one hour’s provisions. Keep enough food for your next voyage.</p>{quote.errors.length>0&&<ul className="warning" aria-live="polite">{quote.errors.map((e,i)=><li key={i}>{e}</li>)}</ul>}<div className="button-row"><button className="primary" disabled={busy||quote.errors.length>0} onClick={()=>perform({type:'trade',lines,expected:quote.token})}>Confirm deal · 1 hour</button><button disabled={busy} onClick={()=>setLines([])}>Clear basket</button></div></>:<p className="muted">Set quantities above to add goods. Sales can fund purchases and free space in the same deal.</p>}</section><p className="muted">One person consumes one provision per day, in port or at sea. Controlled goods await future access mechanics.</p></>;
}
