import {useState} from 'react';
import {CATALOGUE} from './goods';
import {aboard} from './trade';
import {RECIPES,provisionQuote,materialRepairQuote,type FoodGood,type RepairKind} from './operations';
import {currentShip,type Game,type Action} from './game';
type Props={game:Game;busy:boolean;perform:(a:Action)=>void};
export function FoodPreparation({game:g,busy,perform}:Props){
 const [good,setGood]=useState<FoodGood>('grain'),[quantity,setQuantity]=useState(10),q=provisionQuote(g,good,quantity),ship=currentShip(g);
 return <details className="supply-service"><summary>Prepare provisions from food cargo</summary><p>Use food already aboard. Preparation costs 1 silver per input unit and takes 1 hour per 20 units, rounded up. Prepared provisions do not spoil. Normal crew wages and meals continue.</p><div className="trade-filters"><label>Food cargo<select value={good} disabled={busy} onChange={e=>setGood(e.target.value as FoodGood)}>{(Object.keys(RECIPES) as FoodGood[]).map(id=><option key={id} value={id}>{CATALOGUE[id].name} · 1 → {RECIPES[id]} provisions</option>)}</select></label><label>Input quantity<input type="number" min="1" max="200000" step="1" disabled={busy} value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label></div><p>{aboard(g,good).toFixed(2)} {CATALOGUE[good].name} aboard.</p><dl className="full-stats"><div><dt>Output before crew meals</dt><dd>{q.output} provisions</dd></div><div><dt>Preparation fee / time</dt><dd>{q.fee} silver / {q.hours} hours</dd></div><div><dt>Provisions after crew meals</dt><dd>{q.finalProvisions.toFixed(2)}</dd></div><div><dt>Silver after fee and wages</dt><dd>{q.finalSilver.toFixed(2)}</dd></div><div><dt>Hold / weight before crew meals</dt><dd>{q.space.toFixed(2)} / {ship.capacity} space · {q.weight.toFixed(2)} / {ship.deadweight} weight</dd></div><div><dt>Input purchase cost</dt><dd>{q.cost.unknown>1e-8?'Unknown':`${q.cost.total.toFixed(2)} silver`}</dd></div></dl><p className="muted">Prepared food is available to feed the crew during this service. Conversion earns no skill points; prepared provisions retain their recorded costs but earn no Trade learning on resale.</p>{q.errors.length>0&&<ul className="warning" aria-live="polite">{q.errors.map(e=><li key={e}>{e}</li>)}</ul>}<button className="primary" disabled={busy||q.errors.length>0} onClick={()=>perform({type:'prepare-provisions',good,quantity,expected:q.token})}>Confirm preparation</button></details>;
}
export function MaterialRepairs({game:g,busy,perform}:Props){
 const [kind,setKind]=useState<RepairKind>('hull'),q=materialRepairQuote(g,kind);
 return <details className="supply-service"><summary>Supply your own repair materials</summary><p>The shipyard can consume materials from your hold and reduce the cash bill. Compare their purchase cost with the discount; providing cargo is not always cheaper.</p><label>Repair<select value={kind} disabled={busy} onChange={e=>setKind(e.target.value as RepairKind)}><option value="hull">Hull</option><option value="sails">Sails</option></select></label><ul>{q.materials.map(m=><li key={m.good}>{m.quantity.toFixed(2)} {CATALOGUE[m.good].name} · {aboard(g,m.good).toFixed(2)} aboard</li>)}</ul><dl className="full-stats"><div><dt>Full-service price</dt><dd>{q.full} silver</dd></div><div><dt>Material credit</dt><dd>{q.discount} silver</dd></div><div><dt>Remaining cash bill / time</dt><dd>{q.silver} silver / {q.hours} hours</dd></div><div><dt>Materials’ recorded purchase cost</dt><dd>{q.knownCost===null?'Unknown':`${q.knownCost.toFixed(2)} silver`}</dd></div><div><dt>Silver after bill and wages</dt><dd>{q.finalSilver.toFixed(2)}</dd></div></dl><p className="muted">Material quantities are supply units and can be fractional. The credit uses base material values, capped at 60% of the full-service price. Crew wages and provisions continue during work.</p>{q.errors.length>0&&<ul className="warning" aria-live="polite">{q.errors.map(e=><li key={e}>{e}</li>)}</ul>}<button className="primary" disabled={busy||q.errors.length>0} onClick={()=>perform({type:'material-repair',kind,expected:q.token})}>Confirm {kind} repair with cargo</button></details>;
}
