// Shared geography. Keep existing ports first: their event seeds remain stable.
export const PORTS = [
  { id: 'bridgetown', islandId: 'barbados', name: 'Bridgetown', island: 'Barbados', nation: 'England', x: 0, y: 0, prices: { sugar: 8, rum: 16, cloth: 22 }, description: 'Sunlight falls across the quays. Barrels roll toward waiting ships, and the harbour bell marks another hour of business.' },
  { id: 'saint-pierre', islandId: 'martinique', name: 'Saint-Pierre', island: 'Martinique', nation: 'France', x: -29, y: 50, prices: { sugar: 12, rum: 10, cloth: 25 }, description: 'Green slopes rise behind the waterfront. Boatmen call across the roadstead while merchants inspect the morning cargo.' },
  { id: 'willemstad', islandId: 'curacao', name: 'Willemstad', island: 'Curaçao', nation: 'Dutch', x: -285, y: -25, prices: { sugar: 17, rum: 20, cloth: 14 }, description: 'A sheltered harbour opens between busy quays. Cargo from distant shores changes hands beneath the fort’s watchful guns.' },
  {"id": "basse-terre", "islandId": "guadeloupe", "name": "Basse-Terre", "island": "Guadeloupe", "nation": "France", "x": -58, "y": 106, "description": "Carts laden with cocoa creak down from the green hills. Along the quay, coopers hammer hoops onto barrels while a clerk weighs the morning produce."},
  {"id": "capsterville", "islandId": "saint-christopher", "name": "Capsterville", "island": "Saint Christopher", "nation": "France", "x": -105, "y": 148, "description": "A French pennant stirs above the customs office. Provision boats thread between anchored ships, and the steady knock of shipwrights carries across the water."},
  {"id": "st-johns", "islandId": "antigua", "name": "St. John's", "island": "Antigua", "nation": "England", "x": -57, "y": 140, "description": "Canvas hangs from the lofts above the harbour. Sailors bargain over tobacco beneath the watch of a red-coated sentry, with outward-bound ships waiting beyond the quay."},
  {"id": "philipsburg", "islandId": "saint-martin", "name": "Philipsburg", "island": "Saint Martin", "nation": "Dutch", "x": -119, "y": 183, "description": "Salt glints beside the lagoon. Dutch factors compare cotton samples in shaded doorways while lighters ferry bales out to the roadstead."},
  {"id": "san-juan", "islandId": "puerto-rico", "name": "San Juan", "island": "Puerto Rico", "nation": "Spain", "x": -242, "y": 202, "description": "Stone ramparts guard the harbour mouth. Beneath them, tobacco bales pass from warehouse to lighter as a Spanish official checks each departing manifest."},
  {"id": "santo-domingo", "islandId": "hispaniola", "name": "Santo Domingo", "island": "Hispaniola", "nation": "Spain", "x": -369, "y": 207, "description": "Church bells roll over the river anchorage. Hides dry near the warehouses, and mule trains arrive in a cloud of dust with the produce of the interior."},
  {"id": "port-au-prince", "islandId": "hispaniola", "name": "Port-au-Prince", "island": "Hispaniola", "nation": "France", "x": -465, "y": 215, "description": "Small boats crowd the sheltered water beneath wooded hills. Timber merchants argue over measures while coffee sacks disappear into cool stone stores."},
  {"id": "havana", "islandId": "cuba", "name": "Havana", "island": "Cuba", "nation": "Spain", "x": -793, "y": 355, "description": "The harbour opens onto a forest of masts. Guards count silver chests at the quay while shipwrights call for timber from the crowded warehouses."},
  {"id": "santiago", "islandId": "cuba", "name": "Santiago", "island": "Cuba", "nation": "Spain", "x": -606, "y": 260, "description": "Mountains shelter the deep anchorage. Tobacco carts rumble past whitewashed walls, and the ringing of a forge mingles with the calls of boatmen."},
  {"id": "port-royal", "islandId": "jamaica", "name": "Port Royal", "island": "Jamaica", "nation": "England", "x": -619, "y": 185, "description": "Tavern music competes with the boatswains along the busy waterfront. Chandlers pile their counters with tools and rope as merchants seek cargoes for distant ports."},
  {"id": "tortuga", "islandId": "tortuga", "name": "Tortuga", "island": "Tortuga", "nation": "France", "x": -481, "y": 270, "description": "The fort watches a restless anchorage. Tobacco smoke drifts from the taverns, and French merchants keep one eye on their ledgers and the other on arriving sails."},
  {"id": "san-jose", "islandId": "trinidad-tobago", "name": "San Jose", "island": "Trinidad and Tobago", "nation": "Spain", "x": -81, "y": -96, "description": "Warm rain darkens the quay beside the gulf. Coffee and cocoa arrive from inland estates, while boatmen unload sticky casks destined for the shipyards."},
] as const;
export type PortId = typeof PORTS[number]['id'];

export const PORT_IDS = PORTS.map(p=>p.id);
export const ISLANDS = [...new Map(PORTS.map(p=>[p.islandId,{id:p.islandId,name:p.island}])).values()];
export const port = (id:PortId) => PORTS.find(p=>p.id===id)!;
